- content/dstu1/allergy-intolerance.md
- content/dstu1/condition.md
- content/dstu1/diagnostic-report.md
- content/dstu1/encounter.md
- content/dstu1/immunization.md
- content/dstu1/medication-prescription.md
- content/dstu1/observation.md
- content/dstu1/patient.md
- content/dstu2/allergy-intolerance.md
- content/dstu2/immunization.md
- content/dstu2/medication-prescription.md
- content/dstu2/patient.md
Updated search parameter types across all existing pages to directly reflect FHIR types.  Also, removed 'name' from Observation DSTU 1 search parameters.
> Use FHIR parameter types and link to FHIR documentation.

- Rules
- content/faq.md
- content/index.md
- layouts/faq.html
- layouts/faq_sidebar.html
- layouts/header.html
- layouts/highlights.html
- static/css/documentation.css
Did this in a way that matches what is set up for the may2015 and dstu1 sections of the site.  We will be able to add new FAQ sections by adding new faq/*.md files and adding links in faq_sidebar.html
I added links to the FAQ in the header and in the 'highlights' section.
> Establish FAQ section pattern and add FHIR Developers FAQ

- lib/resources/dstu2/types.yaml
- lib/resources/may2015/types.yaml
Verification Steps (running locally):
- On DSTU2 1.0.2 DocumentReference page, ensure the nested Patient, Practitioner, and Encounter links in Reference(Patient, Practitioner, and Encounter) link to http://hl7.org/fhir/DSTU2/(patient/practitioner/encounter).html
- On DSTU2 0.5.0 DocumentReference page, ensure the nested Patient, Practitioner, and Encounter links in Reference(Patient, Practitioner, and Encounter) link to http://hl7.org/fhir/2015May/(patient/practitioner/encounter).html
> Pointing nested Reference links to more specific version url

- README.md
- content/dstu2.md
- content/dstu2/allergy-intolerance.md
- content/dstu2/document-reference.md
- content/may2015.md
- content/may2015/document-reference.md
- layouts/dstu2_sidebar.html
- lib/definition_table_generator.rb
- lib/dstu2_resources.rb
- lib/field_definition_table.erb
- lib/resources/dstu2/allergy_intolerance.yaml
- lib/resources/dstu2/document_reference.yaml
- lib/resources/dstu2/types.yaml
- lib/resources/may2015/document_reference.yaml
- lib/resources/may2015/types.yaml
Changes:
- Adding AllergyIntolerance DSTU2 documentation for Search, Create, and Update
- Enhancing the definition_table logic
- Adding support for flagging fields and values for different action types
- Adding support for simple embedding linking in notes and description fields
- Refactoring type field definition and linking logic to be more straightforward and flexible
- Adding 'top' link to each entry to return to the top of the action
- Updating README.md with documentation on how to use and config the definition_table method
Things to look at when running locally:
- Verify that AllergyIntolerance documentation looks accurate
- Because the type linking was reworked the field names and type links should be looked at again in may2015 and DSTU2. It shouldn't be necessary to verify …
> Adding AllergyIntolerance DSTU2 documentation

- layouts/dstu2_api.html
- layouts/header.html
- layouts/may2015_api.html
* Start Coding uses a local reference and navigates in same window/tab
* The "API" at the top of the page now states version so you know what you're looking at
> Updates to help navigation with new styling

- content/dstu2/document-reference.md
- content/may2015/document-reference.md
- lib/resources/dstu2/document_reference.yaml
- lib/resources/may2015/document_reference.yaml
- Adding "Implementation Notes" section to DocumentReference (may2015 and dstu2) to indicate that we do not support and ignore the relatesTo modifier
- Colonizing the DocumentReference.context.period.end example
> Adding DocumentReference implementation notes

- content/dstu2/observation.md
- lib/dstu2_resources.rb
- lib/resources/dstu2/observation.yaml
* Switch all example urls for Observations to fhir-open to match other examples
* Update tobacco Observation to show the category, form, and question answer Observations
> Update DSTU2 documentation for Observation

- content/dstu2/document-reference.md
- content/may2015/document-reference.md
- lib/resources/dstu2/document_reference.yaml
- lib/resources/may2015/document_reference.yaml
Added more information to eh create description to explain that the document being created must be valid XHTML.
> Update to document reference create description.

- content/dstu2/patient.md
Highlighting the limitations that search by parameters other than _id and identifier:
* are only available in sandbox and not in production.
* will use "fuzzy" search.
Also minor updates to parameter combinations supported.
> Highlight patient search limitations and update parameter combinations

- content/dstu2/care-plan.md
- layouts/dstu2_sidebar.html
- lib/resources/dstu2/care_plan.yaml
- lib/resources/example_json/dstu2_examples_care_plan.rb
- lib/resources/example_json/dstu2_examples_conformance.rb
- lib/resources/example_json/dstu2_examples_relatedperson.rb
Do we need to do anything special for the category terminology binding since we are using the argonaut extension?  Should I just include an example for http://argonaut.hl7.org|assess-plan ?
> Add DSTU2 documentation for CarePlan

- content/dstu2/patient.md
- lib/resources/example_json/dstu2_examples_patient.rb
- Removing the Implementation Notes indicating that Patient.link will not be returned
- Pulling in Overview statement and updating to include Link as a returned field
- Adding a Patient Combines section to the Retrieve By Id section briefly describing the behavior of the link field and when it will be populated
> Updating Patient documentation for Patient.link, extensions, and other changes

- lib/resources/example_json/dstu2_examples_conformance.rb
The CarePlan 'subject' search parameter is currently functional but is not included in the server's conformance document.
Once the change goes out to include it in the conformance, we can merge this pull request to get the example updated.
> Update CarePlan Conformance

- content/dstu2/authorization.md
A first stab at documenting the "mange" extension. I tried to integrate the terminology here http://docs.smarthealthit.org/authorization/conformance-statement/  with the current documentation style. 
I feel like it's a little wordy
> Updating Authorization documentation to include discussion of “manage” extension.

- content/millennium/dstu2/encounters/encounter.md
Updates Encounter page to include authorization header for each action.  Uses same format as [Patient](http://fhir.cerner.com/millennium/dstu2/individuals/patient/#authorization-types).  Encounters are only authorized for Practitioner and System.
> Add authorization header to Encounter actions

- content/millennium/dstu2.md
There is a space before the octothorpes causing Resource Identity to not render correctly.
> Render Resource Identity correctly by remove extra space

- content/millennium/dstu2/general-clinical/condition.md
- lib/resources/dstu2/condition.yaml
- lib/terminology_table.erb
Added the template to Condition. Resulted in adding authorization types as well as the operation outcomes that can be returned.
Also: separated system from the link for more info for the terminologies table so I could fix the system definitions. Will be applying this to remaining resources as we move forward.
> Apply template to Condition, add accepted Authorization Types

- content/millennium/dstu2/individuals/practitioner.md
- lib/resources/example_json/dstu2_examples_practitioner.rb
Update Millennium Practitioner documentation and examples to reflect that birth date is no longer returned
> Remove birth date from Millennium Practitioner

- content/millennium/dstu2/infrastructure/binary.md
Updates Binary resource documentation to reflect upcoming changes around support for reading documents with pdf content type.
> Documentation for Binary PDFs

- content/millennium/dstu2/structure-definition.md
- layouts/millennium_dstu2_sidebar.html
- lib/resources/example_json/dstu2_examples_structure_definition.rb
Adds documentation for StructureDefinition.  
A couple things I could use feedback on:
- Do we want to list the custom extensions for which we define StructureDefinitions?  We do something similar in OperationDefinition.
- If so, I could use some help thinking of appropriate descriptions for each of the extensions.  I've gone ahead and included them and taken a shot at describing them.
> Add Documentation for StructureDefinition

- content/millennium/dstu2/infrastructure/document-reference.md
- lib/resources/example_json/dstu2_examples_document_reference.rb
Updates documentation for new DocumentReference read/search by ID functionality.  Also updates example search parameters to be usable values with the open sandbox instance.
We'll need to wait a few days before this can be merged, but I wanted to go ahead and get it out here for review.
> Add Documentation for DocumentReference Read and Search by ID

- content/smart.md
Add a note about the browser version limitation (IE10) when application is rendered within *MPages* 6.x platform.
@kpshek 
@daliboz 
@shriniketsarkar 
@zplata
> Add a note about IE version limitation (IE10) in MPages

- lib/resources/dstu2/immunization.yaml
Add the bindings for NDC to the Immunization bindings list for vaccineCode, including a note.
> Add NDC to Immunization bindings for vaccineCode

- content/authorization/authorization-specification.md
Current rendering:
Fixed rendering:
This was the only place on the site I saw \<sup>\</sup> tags in a title
> Remove <sup></sup> from authorization-specification title

- content/authorization.md
Remove citation to a now-expired IETF RFC draft, and add citation to the document that replaced it.
> Update RFC citations

- content/millennium/dstu2/individuals/patient.md
We don't use US Core in DSTU 2, make sure the link text is more clear
> Remove US Core references

- layouts/millennium_dstu2_sidebar.html
This makes sure that the TOC stays open when navigating to the ProcedureRequest page.
> Fix ProcedureRequest TOC Link

- content/millennium/dstu2/scheduling/appointment.md
Appointment creation now displays only the Practitioner and System authorization types.
> Remove 'Patient' from Appointment creation auth types

- content/millennium/dstu2/infrastructure/document-reference.md
- lib/definition_table_generator.rb
- lib/field_definition_table.erb
- lib/resources/dstu2/document_reference.yaml
- lib/resources/example_json/dstu2_examples_document_reference.rb
adding documentation for docRef proprietary codes
- Update read by ID example to reflect return of  proprietary codes
- Update documentation to reflect DARs on type if mappings for LOINC are missing
- Update create documentation to reflect support of proprietary codes
> docRef proprietary codes documentation

- content/millennium/dstu2/scheduling/appointment.md
- lib/resources/dstu2/appointment.yaml
Appointment creation now displays the .slot body field as a list containing a single reference to a Slot.
> Appointment Creation accepts .slot as a list

- lib/resources/example_json/r4_examples_encounter.rb
The Encounter Read and Search examples did not HTML escape the narrative in the JSON examples. It needed to be added so that the view rendered the HTML as code instead of rendering the HTML itself.
Validation:
Make sure the Encounter narratives are displaying HTML code.
> HTML escaping the narratives in the Encounter read and search examples

- content/millennium/r4/devices/device.md
- lib/resources/example_json/r4_examples_device.rb
r4_examples_device contained some non-escaped < characters. escaped them in f4d8fee
R4 device.md contained some extra whitespace. removed it in 97a62a3
> kramdown warning when compiling site

- lib/resources/r4/related_person.yaml
the name of valueset-identifier-type is "Identifier Type Codes"
the name of code set 36 is "Languages"
the name and URL of code set 40 are "Person Relationships"
> Tweak R4 RelatedPerson terminology displays and fix Millennium PersonRelationships link. Fixes #309

- lib/resources/r4/allergy_intolerance.yaml
Adding RxNorm to the terminology bindings for r4. It's already documented in DSTU2, just updated in R4.
> Adding AllergyIntolerance terminology binding: RxNorm

- content/millennium/dstu2/proprietary-codes.md
- content/millennium/r4/proprietary-codes-and-systems.md
When writing a proprietary code there will be a failure if standard codes are supplied as well. This affects DocumentReference writes in DSTU2 and all writes in R4. The documentation for proprietary codes now notes that when standard codes are provided on a write they will cause the write to fail.
> Add warning against writing both standard and proprietary codes

- lib/resources/example_json/dstu2_examples_medication_order.rb
- lib/resources/example_json/dstu2_examples_medication_statement.rb
Changed the expected response when calling a GET on medication order and medication statement to reflect that the _count/pageSize is no longer being defaulted.
> Removed a defaulted returned count on medication order and medication statement

- content/millennium/dstu2/devices/device.md
The goal of these changes were to add a disclaimer to request examples in the Device resource that the data may be different than the response shown.
Verifcation:
> Devices Json Inconsistencies

- content/millennium/dstu2/encounters/encounter.md
The goal of these changes were to add a disclaimer to request examples in the Encounter resource that the data may be different than the response shown.
Verification:
> Encounters JSON Inconsistencies

- content/millennium/dstu2/diagnostic/diagnostic-report.md
- lib/resources/example_json/dstu2_examples_diagnostic_report.rb
DiagnosticReport now returns a title in PresentedForm, so here is an updated Overview and JSON example.
Pics of changes running locally:
Overview:
JSON example:
> Add presentedForm.title to DiagnosticReport

- content/millennium/dstu2/infrastructure/document-reference.md
- lib/resources/example_json/dstu2_examples_document_reference.rb
- static/css/documentation.css
Document Reference now returns a title in Docref.content.attachment on reads/searches, so here is an updated overview and JSON example.
Pics from running locally:
Overview:
JSON update:
> Add content.attachment.title to DocumentReference

- lib/resources/r4/appointment.yaml
This change removes reasonCode from the R4 Appointment create body fields table. We did not set an action key in the R4 Appointment yaml file until now. R4 Appointment create ignores reasonCode if it is set.
Local verification - comment is now the final field in the create body fields table:
Fixes #339
> Set action to terminology for R4 Appointment reasonCode

- content/authorization.md
Fix typos in authorization doc (Thanks John Moses for reporting this)
> Fix typos in authorization doc

- lib/resources/r4/medication_request.yaml
- lib/resources/r4/medication_request_contained_medication.yaml
I updated the MedicationRequest.medication[x] terminology field to display RxNorm.
screenshot:
> Update MedicationRequest.medication[x] terminology display

- content/millennium/dstu2/medications/immunization.md
- content/millennium/dstu2/medications/medication-administration.md
- content/millennium/dstu2/medications/medication-order.md
- content/millennium/dstu2/medications/medication-statement.md
- lib/resources/example_json/dstu2_examples_medication_statement.rb
I went through the DSTU2 Medications section and fixed some inconsistencies with the JSON.
**MedicationStatement**:
The current create example does not work so I updated the Patient to one that exists, so that it does.
EX:
The Update throws a 404, so I updated it to use a currently existing MedicationStatement and Patient. This call will not succeed since it has already been updated to complete, but now that it is tied to an existing MedicationStatement a user can read that resource to see its status.
EX:
**All**:
I also went through and added the disclaimer to all the Medications response examples.
EX:
> Update Medications JSON inconsistencies

- content/authorization.md
Proposing an example cURL to highlight for developers to create a system token.
I'm adding a second scope to the `scopes` example, just to highlight to developers that scopes are space-delimited.
> Add example System Account token request

- content/millennium/dstu2/diagnostic/diagnostic-report.md
- content/millennium/dstu2/diagnostic/observation.md
I checked both Diagnostic resources for any major JSON inconsistencies, but I found none. I then added the disclaimer after their example responses.
> Add disclaimers to Diagnostic JSON examples

- content/millennium/dstu2/individuals/patient.md
- content/millennium/dstu2/individuals/practitioner.md
- content/millennium/dstu2/individuals/related-person.md
- lib/resources/example_json/dstu2_examples_patient.rb
Patient, Practitioner, and Related Person updates.
Added disclaimers to responses where data may not be the same in FHIRPLAY, and updated the combine example with valid combined patient.
Patient update:
Practitioner update: 
Related Person update:
> Individuals JSON Inconsistencies Update

- content/millennium/r4/diagnostic/observation.md
- lib/resources/example_json/r4_examples_observation.rb
Documentation for r4 Observation will be updated to include the fields Identifier and Performer.
Local verification:
> Updated r4 Documentation for Observation to include Identifier and Performer

- content/millennium/r4.md
- content/millennium/r4/general-clinical/condition.md
- lib/resources/example_json/r4_examples_capabilitystatement.rb
Add documentation to show that diagnosis is supported in R4 Condition reads and searches. 
**Validation**
- Search
- Open Metadata
- Closed Metadata
> Add documentation for R4 Condition diagnosis read/search

- content/millennium/dstu2/entities/person.md
- content/millennium/dstu2/individuals/patient.md
Description
There were a couple of missing disclaimers that needed to be added to the docs.
PR Checklist
----
Before Changes Merged: 
Patient Disclaimer
Person Disclaimer
> Add DSTU2 Person/Patient Disclaimers

- content/millennium/r4/medications/medication-request.md
Description
----
This PR adds clarification stating that we are currently hard-coding MedicationRequest intents to "ORDER" on reads and searches, and to use the reported field to determine if a medication is a authorized or a request by a patient.
I wasn't 100% sure where we wanted this information, so I added it as a note under the field in the Overview section. Let me know if we want this worded or laid out differently (like adding it to both the read and search sections separately or something).
PR Checklist
----
> Clarified state of MedRequest intent.

- content/millennium/dstu2.md
- content/millennium/r4.md
- content/millennium/r4/encounters/encounter.md
- content/soarian/dstu2.md
- lib/resources.rb
Description
----
- Document that R4 Encounter Bundles are sorted by the Encounter.period
- Update Bundle Page links to include the Previous link
PR Checklist
----
> Add R4 Encounter sorting details, update Pagination with previous link

- lib/resources/example_json/r4_examples_allergy_intolerance.rb
Description
----
Remove a couple duplicated JSON keys
PR Checklist
----
> Remove duplicated fullUrl and resource keys from AllergyIntolerance search JSON example. Fixes #401

- lib/resources/r4/appointment.yaml
Description
----
Added the missing `required` field for reasonCode in appointment.yaml
PR Checklist
----
> Added required field for reasonCode. Fixes #404

- content/millennium/r4/financial/account.md
Description
----
Account search by patient with type 'statement' requires the identifier to have system codeSet 28200. Currently, is not clear that system 'https://fhir.cerner.com/accountnumber' cannot be used when type is 'statement'.
Account search by patient with type 'financial-account' is not currently supported
Validation
---
PR Checklist
----
> R4 Account search clarification

- lib/resources/r4/patient.yaml
Description
----
The R4 documentation for Patient was updated to reflect the character limits for its string fields.
Validation
----
The following changes are present on the body-fields table of Create section:
a) Patient.name character limits on family, given, prefix, and suffix
b) Patient.telecom character limit on value
c) Patient.address character limits on line, city, district, state, postalCode, and country
UPDATE: See https://github.com/cerner/fhir.cerner.com/pull/414#issuecomment-652500157 for updated screenshots.
PR Checklist
----
> Updated patient resource to reflect string field character limit

- content/millennium/dstu2/conformance/conformance.md
- content/millennium/dstu2/devices/device.md
- content/millennium/r4/conformance/capability-statement.md
- content/millennium/r4/devices/device.md
- layouts/head.html
- layouts/millennium_diff_table.html
- lib/request_button.rb
- spec/lib/request_button_spec.rb
- static/css/documentation.css
- static/js/documentation.js
- static/js/millennium_diff_table.js
- static/js/request_button.js
Description
----
Added tabs to the examples on metadata and on the Device resource. Clicking the live response tab fires a request and displays the result. The example requests have been replaced with cURL commands. 
PR Checklist
----
> Add live request button to metadata and Device endpoints

- content/millennium/dstu2/infrastructure/document-reference.md
Fixes #422
Description
----
Fix date format and bounds on parameter example; format table
PR Checklist
----
> Fix DSTU 2 DocumentReference created parameter example

- content/millennium/r4/individuals/practitioner.md
- lib/resources/example_json/r4_examples_practitioner.rb
Description
----
Add sample url calls to search and retrieve by id of R4 Practitioner to showcase Patient Access response. In addition, update previous examples to show more fields in the response to better differentiate between Provider, System access and Patient access.
Validatoin
----
Search:
Retrieve by Id
PR Checklist
----
> R4 Practitioner add patient access sample urls

- lib/definition_table_generator.rb
- lib/resources/r4/coverage_encounter_patch.yaml
Description
----
Update our custom yaml processing to allow fhirpath array indices to pass through
Fixes #418 
PR Checklist
----
> Prevent numbers inside square brackets in yaml files from being activated as links. Fixes #418

- content/millennium/r4/scheduling/appointment.md
- lib/resources/r4/appointment_patch.yaml
Description
Updated the Appointment 'patch' request to have 'fulfilled' status
With this enhancement, the Appointment resource can support updating the status of an appointment from booked to fulfilled.
--------------------------------------------**Screenshot Before Merge:**---------------------------------------
--------------------------------------------**Expected Screenshot After Merge:**-------------------------------
(changes: a new status 'fulfilled' is added)
----
PR Checklist
----
> Appointment request patch status field to 'fulfilled'

- content/millennium/dstu2/scheduling/appointment.md
- lib/resources/r4/appointment_patch.yaml
Description
----
It was discovered that the Cerner Video's database for appointments requires all strings to be 255 characters or less. This was tested via Postman calls to Cerner Video's code and to FHIR through PATCH requests. FHIR code will be modified to return a 422 response in this case.
Before Change
----
Add Patch
Replace Patch
Potential Errors
After Change
----
Add Patch
Replace Patch
Potential Errors
PR Checklist
----
> Max Appointment URL Length

- content/millennium/r4/encounters/encounter.md
Description
----
We need to link the word 'reference' to two different pages within the R4 encounter page, so one of the links has to be inline. Fixes #417
PR Checklist
----
> Support simultaneously linking reference and Reference in R4 Encounter. Fixes #417

- content/millennium/dstu2/general-clinical/condition.md
- lib/resources/dstu2/condition.yaml
Description
----
Duplicate information about Condition.encounter being required for diagnoses to increase clarity
Fixes #344
PR Checklist
----
> Add note that DSTU 2Condition.encounter is required for diagnoses to the body fields table

- content/millennium/r4/financial/financial-transaction.md
- lib/resources/example_json/r4_examples_financial_transaction.rb
- lib/resources/r4/financial_transaction.yaml
Description
----
- Updating examples to use real financial-transaction-location ids from C1941. location id 98920358
- Updating examples to use real encounter ids for allocation.target from C1941. Encounter/97953536
- Updating payment examples to use real financial-transaction-alias ids from C1941. alias 0111 (Note that the adjustment example should stay the same.)
- Removing the implementation note of "A FinancialTransaction can only be targeted at a clinical Encounter that has related financial activity/encounters within the Cerner Revenue Cycle Patient Accounting system.”
- Removing the word "production" from the implementation note so it reads "When integrating your application with a client’s environment, the client will have to provide the appropriate financial-transaction-alias …
> fhir documention update for financial transaction

- content/millennium/r4/conformance/structure-definition.md
- content/millennium/r4/encounters/encounter.md
- lib/resources/example_json/r4_examples_encounter.rb
Description
----
Encounter custom-attribute documentation without terminology binding documentation because Kathy is OOO until Friday. PR that includes terminology binding information: https://github.com/cerner/fhir.cerner.com/pull/438
Screenshots of changes before merge
----
PR Checklist
----
> Encounter r4 Custom-Attribute Extension

- content/millennium/r4/documents/document-reference.md
- lib/resources/r4/document_reference.yaml
DocumentReference add Mime types text/plain and text/richtext
Description
----
Add supported Mime types to content.attachment.content_type
PR Checklist
----
> Update document-reference.md with plain and richtext Mime types

- content/millennium/r4/proprietary-codes-and-systems.md
- lib/resources/example_json/r4_examples_encounter.rb
- lib/resources/r4/encounter.yaml
Description
----
Updating the encounter resource to include the custom-attribute extension terminology binding information.
This PR is a follow-up to these fhir.cerner.com updates found here: https://github.com/cerner/fhir.cerner.com/pull/471
Screenshots before changes merged
----
PR Checklist
----
> Encounter r4 Custom-Attribute Extension Terminology Binding Update

- lib/resources/r4/appointment.yaml
Description
----
Update serviceType create example to not use proprietary code as this is not yet supported
PR Checklist
----
> [R4][Appointment] Update serviceType create example to not use proprietary code

- content/millennium/dstu2/general-clinical/condition.md
- content/millennium/r4/general-clinical/condition.md
Description
----
Added description on the implementation note section for how code.coding field behaves in DSTU2 and R4
PR Checklist
----
> Added description for Condition.code field in DSTU2 and R4.

- lib/resources/dstu2/condition.yaml
Description
----
Added note for Condition.clinicalStatus field update action in DSTU2
Added note on the implementation note section for how code.coding field behaves in DSTU2 and R4
PR Checklist
----
> Added note for Condition.clinicalStatus field update action in DSTU2

- content/millennium/dstu2/general-clinical/condition.md
- lib/resources/dstu2/condition.yaml
- lib/resources/example_json/dstu2_examples_condition.rb
Description
----
Removed asserter field from Condition DSTU2 since it is now being deprecated
PR Checklist
----
> Removed asserter field from Condition DSTU2

- lib/resources/example_json/r4_examples_observation.rb
Description
----
The R4 Observation lab Create and Update examples have a valueQuantity.value of `"13.2"`, but should be a numeric value of `13.2`.
PR Checklist
----
Before merge:
Create
Update
> Fix R4 Observation Create/Update examples' valueQuantity.value to numeric instead of string

- content/millennium/r4/financial/coverage.md
Description
----
Fix typo in Coverage Search endpoint.
Pre-merge changes:
PR Checklist
----
> Fix R4 Coverage Search typo

- content/millennium/r4/documents/document-reference.md
- lib/resources/example_json/r4_examples_document_reference.rb
- lib/resources/r4/document_reference.yaml
- lib/resources/r4/document_reference_docref.yaml
DocRefCcd support added for Document reference
Description
----
DocRefCcd support added for Document reference
PR Checklist
----
> R4_docref_ccd_support

- static/js/millennium_diff_table.js
Description
----
Due to the way sorting of both of the arrays together was accomplished previously, the loop was prematurely ended as DSTU2 resources were completely parsed through. The alterations to the function should now properly sort through the array and reduce the potential future risks of omitting resources as we are using a `for` loop rather than a `while` loop. Resources are sorted, as the documentation states, first by the R4 resource name, if it exists, then the DSTU2 resource (if. there is no matched R4 resource).
PR Checklist
----
> Fix Millennium Overview Table Sorting; Add CarePlan and Contract configuration

- content/millennium/r4/individuals/practitioner.md
Description
----
Adding `given` and `family` parameters to Practitioner search
PR Checklist
----
> Add 'given' & 'family' to practitioner search parameters

- lib/resources/example_json/r4_examples_relatedperson.rb
Description
----
Updating the name.id field on RelatedPerson Encounter read/search request examples after correcting a defect.
Screenshots before changes merged
----
PR Checklist
----
> RelatedPerson Encounter Read/Search Name.id Update

- content/millennium/dstu2.md
- content/millennium/dstu2/general-clinical/allergy-intolerance.md
- content/millennium/dstu2/general-clinical/condition.md
- content/millennium/dstu2/individuals/patient.md
- content/millennium/dstu2/infrastructure/document-reference.md
- content/millennium/dstu2/medications/medication-statement.md
- content/millennium/dstu2/scheduling/appointment.md
- content/millennium/r4.md
- content/millennium/r4/diagnostic/observation.md
- content/millennium/r4/documents/document-reference.md
- content/millennium/r4/encounters/encounter.md
- content/millennium/r4/entities/organization.md
- content/millennium/r4/financial/coverage.md
- content/millennium/r4/financial/financial-transaction.md
- content/millennium/r4/general-clinical/allergy-intolerance.md
- content/millennium/r4/general-clinical/condition.md
- content/millennium/r4/general-clinical/procedure.md
- content/millennium/r4/individuals/patient.md
- content/millennium/r4/individuals/practitioner.md
- content/millennium/r4/individuals/related-person.md
- content/millennium/r4/medications/immunization.md
- content/millennium/r4/medications/medication-request.md
- content/millennium/r4/security/provenance.md
Fixes #397
Description
----
Some response headers are auto-added by the server and may change at any time, so we should focus our documentation around response headers that are meaningful
PR Checklist
----
> Remove non-purposefully added response headers, standardize response header formatting

- content/smart.md
Description
----
Current link on this page to HAPI doc is dead, current link to .NET doc points to a redirected repo. Fixes #545 
PR Checklist
----
> Update SMART Open Source FHIR Client Libraries links

- content/millennium/r4/documents/document-reference.md
- lib/resources/example_json/r4_examples_document_reference.rb
Description
----
Added patient access for R4 Document Reference CCD search
----
PR Checklist
----
> Added patient access for R4 Document Reference CCD search

- lib/resources/example_json/r4_examples_relatedperson.rb
- lib/resources/r4/related_person_patch.yaml
Description
----
The change in r4_examples_relatedperson.rb fixes an accidentally-escaped quote character
The change in lib/resources/r4/related_person_patch.yaml fixes a slew of rendering issues caused by that missing HTML tag
PR Checklist
----
> Fix a few typos in R4 RelatedPerson

- lib/resources/example_json/r4_examples_patient.rb
- lib/resources/r4/patient.yaml
- lib/resources/r4/patient_patch.yaml
Description
----
The documentation for the R4 Patient.telecom additions for the phone extensions. This shows an example of the phone extension returned through the Patient.telecom.extension field. A phone extension value was also added to show how to write the data when creating a patient, and also for the PATCH operation to add a new telecom. Lastly, the telecom/extension replace operation is described, which is the capability to replace the phone extension on an existing telecom.
PR Checklist
----
Screenshots
----
> Added R4 Patient Phone Extension

- lib/resources/example_json/r4_examples_relatedperson.rb
- lib/resources/r4/related_person_patch.yaml
Description
----
Added remove operation for telecom field in related person patch capability.
PR Checklist
----
> Updated related person remove telecom operation

- content/millennium/dstu2/general-clinical/condition.md
- content/millennium/r4/general-clinical/condition.md
Description
----
Adds a new R4 Condition create immplementation note:
```
An `encounter-diagnosis` Condition will be automatically prioritized to the least significant priority by the Cerner Millennium EHR
```
and rewords some of the others for clarity
PR Checklist
----
> Update implementation notes for R4 Condition create

- content/millennium/r4/financial/coverage.md
- lib/resources/example_json/r4_examples_coverage.rb
- lib/resources/r4/coverage_encounter_patch.yaml
Description
----
Adding the patient/encounter level public healthcare searches and patches. Documentation that explains the changes, including examples of the public healthcare reads, and details of the patch capabilities, and limitations, for the public healthcare coverages.
PR Checklist
----
Screenshots
----
> Updating R4 Coverage with Patient and Encounter Level Public Healthcare Searches and Patches

- content/millennium/r4/scheduling/slot.md
- lib/resources.rb
- lib/resources/example_json/r4_examples_slot.rb
- lib/resources/r4/slot_patch.yaml
- spec/lib/resources_spec.rb
- static/css/documentation.css
Description
----
Added replace operation for R4 Slot
Screenshots
----
PR Checklist
----
> Slot status patch

- content/millennium/r4/definitional-artifacts/questionnaire.md
- lib/resources/example_json/r4_examples_questionnaire.rb
Description
----
Questionnaire now exposes the note-allowed extension on the item instead of the comment question
PR Checklist
----
> Questionnaire note-allowed extension

- content/millennium/r4/scheduling/appointment.md
Description
----
Removing the [5-100] count param range in appointment search.
Evidence captured [here](https://gist.github.com/sujanb12/f608585e8223f1b6930feaf5f7bce759) to ensure that  Appointment search with count parameter outside of [5-100] is not throwing 400 Bad request. 
PR Checklist
----
> [Appointment][R4] Documentation update for search by _count parameter

- content/millennium/r4/conformance/structure-definition.md
- content/millennium/r4/financial/charge-item.md
Description
----
This pr adds a new custom extension 'replacing' to the structure definition and charge Item structure definition list
PR Checklist
----
> [ChargeItem] [R4] Add 'replacing' custom extension 

- content/millennium/r4/financial/coverage.md
Description
----
Updating documentation to include Delete information on Public Healthcare coverages. Also clarifying the difference between private/public coverages more.
Before Merge Screenshots
----
PR Checklist
----
> R4 Coverage Public Healthcare delete

- lib/resources/example_json/dstu2_examples_document_reference.rb
- lib/resources/r4/document_reference.yaml
Description
----
PR Checklist
----
> Fix DocumentReference.type info when loinc is missing

- content/millennium/r4/definitional-artifacts/questionnaire.md
Description
----
Remove beta tag from Questionnaire
PR Checklist
----
> Remove beta tag from Questionnaire

- content/millennium/r4/definitional-artifacts/questionnaire.md
- content/millennium/r4/diagnostic/questionnaire-response.md
- lib/resources/example_json/r4_examples_questionnaire_response.rb
- lib/resources/r4/questionnaire_response.yaml
- lib/resources/r4/types.yaml
Description
----
QuestionnaireResponse read/search are no longer mocked out, we need to update fhir.cerner.com to show the supported fields
We need to mention:
QR comes back even when they have no data (as long as the patient exists)
The workflow should be (for social history questionnaires):
Search QR by patient
Get the ‘questionnaire’ field from the QR
Retrieve that Questionnaire
We only support answer value types of: String, Quantity, and Coding
How do QRs relate to Observations?
Before Merge Screenshots
----
PR Checklist
----
> QuestionnaireResponse Supported Fields Update

- content/millennium/r4/diagnostic/observation.md
- lib/resources/r4/observation.yaml
Description
----
Vital Sign creates support provider persona. Labs Creates support additional performers like PRF and AUTHEN whereas vitals   support PPRF.
PR Checklist
----
> Vital Sign Create supports Provider Persona

- content/millennium/r4/foundation/documents/document-reference.md
- lib/resources/example_json/r4_examples_document_reference.rb
Description
R4 DocumentReference search by encounter should not return patient level documents
Screenshots
PR Checklist
----
> search by encounter filters patient level document

- content/millennium/r4/foundation/other/health-cards.md
Description
----
Removed beta tag for health-cards
PR Checklist
----
> Remove beta tag for health-cards

- content/authorization.md
Description
----
This Q&A is stale (and misleading) ever since the option for public vs. private client became available in the developer portal:
Before Changes:
PR Checklist
----
> Remove stale Q&A from authorization overview

- content/millennium/r4/clinical/diagnostics/observation.md
- lib/resources/example_json/r4_examples_observation.rb
Description
----
Added support for RevInclude search for R4 Observation
PR Checklist
----
> R4 Observation: support _revinclude provenance for Observation

- content/authorization.md
Description
----
In the course of testing related to the 21st Century Cures Act (using the ONC's "Inferno" test suite), some questions arose related to the Authorization Server's handling of token revocation; these changes attempt to clarify those behaviors.
PR Checklist
----
> Clarify token revocation behavior

- content/millennium/r4/clinical/summary/family-member-history.md
Description
----
Remove if-match and etag header for FamilyMemberHistory
PR Checklist
----
> R4 FamilyMemberHistory: Remove if-match and etag header

- lib/resources/r4/medication_request.yaml
- lib/resources/r4/medication_request_contained_medication.yaml
Description
----
There is some inconsistent documentation on codesets in the terminology bindings and what we return in json from responses. So just cleaning up those in this PR.
<details>
<summary>The Before Images</summary>
Status/Reason/Category
Priority/Medication[x]/reasonCode
dosageInstruction.timing.code
Contained medication code
</details>
PR Checklist
----
> R4 MedicationRequest: fix secure protocol codeset term bindings to be more consistent

- content/authorization/tls-guidance.md
- layouts/authorization_sidebar.html
- nanoc.yaml
Description
----
Added guidance for developers for the correct usage of TLS in conjunction with Cerner Ignite.  This was a remediation task from an incident with a third-party application that performed certificate pinning, rather than using traditional PKI-based certificate verification for our services.
PR Checklist
----
> Added TLS Usage guidance

- content/millennium/r4/financial/general/charge-item.md
- lib/resources/example_json/r4_examples_charge_item.rb
Description
----
fhir.cerner.com changes for ServiceRequest (OrderID) in chargeItem responses for Read, Search and Write
PR Checklist
----
> R4 ChargeItem: Supporting Information field changes

- content/millennium/r4/clinical/diagnostics/questionnaire-response.md
the search example has the resource questionnaireresponses instead of questionnaireresponse.  Updated the example.
Description
----
PR Checklist
----
> Update QuestionnaireResponse search example

- content/millennium/r4/financial/general/charge-item.md
- lib/resources/r4/charge_item_create.yaml
- lib/resources/r4/charge_item_modify.yaml
Description
----
Update documentation to support a valueDateTime for custom-attribute from a valueDate
Screenshots Before Changes Merged
----
Documentation update to charge-item-modify:
Documentation update to charge-item-create:
PR Checklist
----
> ChargeItem custom-attribute valueDateTime

- lib/resources/example_json/r4_examples_encounter.rb
- lib/resources/r4/encounter.yaml
Description
----
Documentation for encounter create custom-attribute type string support.
Screenshots before changes merged
----
PR Checklist
----
> Encounter Create custom-attribute type string

- content/authorization.md
Description
----
The current link (without ".html") shows a 404 page. Adding the extension returns the expected content.
PR Checklist
----
> Update broken link for Authorization "Wildcard scopes"

- content/millennium/r4/proprietary-codes-and-systems.md
Description
----
Updated the Millennium R4 Proprietary codes and systems page for multi-region support.
Screen shots of the updates:
PR Checklist
----
> Update proprietary code system page for multi-region support

- lib/resources/r4/document_reference.yaml
Description
----
Removed unwanted DocumentReference.type from terminology bindings
PR Checklist
----
> updated R4 documentReference terminology bindings

- content/authorization.md
Satisfies one of the requirements of the 21st Century Cures Act, specifically: 170.315(g)(10)(v)(A)(1)(iii)
https://www.healthit.gov/sites/default/files/page/2021-07/Clarifications_For_Native_Apps_v5.pdf
> In the Interim Final Rule, ONC clarified that health IT developers must publish the method(s) by which their Health IT Modules support the secure issuance of an initial refresh token to native applications.
Description
----
PR Checklist
----
> Clarify handling of refresh tokens for native applications

- Rules
- lib/resources/example_json/r4_examples_encounter.rb
- lib/resources/r4/encounter.yaml
Description
----
Updating read/search examples to include the custom-attribute id and add a note about it not being supported to create documentation.
Retrieve update:
Search update:
Create note:
PR Checklist
----
> R4 Encounter custom-attribute id documentation

- .gitignore
- content/authorization.md
Description
----
With the new auto-suspension capabilities in the authorization server that are based on evaluations of external application DNS TXT records and TLS certificates, the documentation needed to be updated to provide more detailed instructions on how to get refresh tokens re-approved by the end user.
PR Checklist
----
> Added documentation for suspended refresh tokens

- content/smart.md
As an engineer: I want to include a section on UI/UX recommendation relating to having a loading indicator / spinner in the current documentation @ https://fhir.cerner.com/smart
So that: the developers would consider the suggestion and build their app to include a loading indicator/spinner when the app loads and fetch any data from FHIR to give the users a better user's experience and indication of progress
> Loading indicator suggestion

- content/millennium/r4/foundation/other/health-cards.md
Description
Update broken links (DM Profiles) on fhir.cerner.com in the health-cards section 
PR Checklist
Health Cards documentation page with links to broken pages (e.g. VaccinationCredentialPatientDM)
The 404 page displayed for VaccinationCredentialPatientDM broken link :
----
> Updated DM Profile Links for health-cards API

- content/millennium/r4/base/individuals/patient.md
- static/js/millennium_diff_table.js
- static/js/millennium_diff_table_config.js
Description
----
Remove the Group resource from the Millennium Resources Table.
Fix Health Cards link in Patient resource documentation.
Dev Validation
----
PR Checklist
----
> Remove Group from resouces table and fix health cards link

- content/millennium/r4/base/management/encounter.md
Description
----
In R4 Encounter, the notes section under search parameters has a misspelling.
PR Checklist
----
Before changes merged:
----
> R4 Encounter updated search parameter notes

- content/authorization.md
Description
----
As part of the work for the 21st Century Cures Act, we now _do_ advertise a RFC 7009 endpoint at /.well-known/smart-configuration, making this documentation out-of-date and misleading. See also: http://fhir.cerner.com/millennium/r4/foundation/conformance/capability-statement/#example
PR Checklist
----
> Remove out-of-date documentation re: revocation

- content/millennium/dstu2/individuals/patient.md
- content/millennium/r4/base/individuals/patient.md
added a new note to the Notes section in patient search for both R4 and DSTU2 the new line is:
* It is recommended that when searching for a patient to not combine `family`, or `family` and `given`, with `name` key, and use the ':exact' modifier when possible.
Description
----
PR Checklist
----
> patient-r4-dstu2-search-notes-update

- content/millennium/r4/clinical/diagnostics/observation.md
Description
----
Updated constraints of r4_observation _count parameter
PR Checklist
----
> R4 observation count update

- content/millennium/r4/base/workflow/slot.md
Description
----
Adding system/Schedule.read as one of the allowed scopes when searching by _include for Millennium R4 Slot.
PR Checklist
----
> Updating which scopes may be included when using the _include parameter on Slot for Millennium R4

- content/authorization/active-user-presence.md
Description
----
It seems that nanoc's rendering capabilities differ slightly from GitHub's built-in Markdown renderer; applying a correction here that was suggested by @Someshnsn. Fixes https://github.com/cerner/fhir.cerner.com/pull/929, which (as actually published to fhir.cerner.com) doesn't currently look correct.
PR Checklist
----
> Correct diagram rendering

- content/millennium/r4/clinical/summary/allergy-intolerance.md
- lib/resources/example_json/r4_examples_allergy_intolerance.rb
Description
----
Added general info (similar to how the precision extension was added to Family Member History see http://fhir.cerner.com/millennium/r4/clinical/summary/family-member-history/#extensions-1)
Added the extension content to the "Search" action response body (similar to http://fhir.cerner.com/millennium/r4/clinical/summary/family-member-history/#search)
Addedthe extension content to the "Retrievey by id" action response body (similar to http://fhir.cerner.com/millennium/r4/clinical/summary/family-member-history/#retrieve-by-id)
PR Checklist
----
> Added documentation for AllergyIntolerance onset datetime precision extension

- content/millennium/faq/common-issues.md
Description
----
The example HTML for the APPLINK functionality is invalid HTML—and JavaScript. This updates that example to the correct, expected syntax.
PR Checklist
----
> Fix APPLINK example code

- content/authorization.md
Description
----
Rework of the Chapter III, section IV to remove "status" parameter for the token request and added reference to "redirect_uri" parameter when this was used to ask for authorization per official documentation https://www.rfc-editor.org/rfc/rfc6749#section-4.1.3.
PR Checklist
----
> Rework chapter III section IV

- layouts/head.html
Description
----
~~Current Analytics tags are expiring 1 July and need to be updated for continued use.~~
Due to Oracle's technology ban on GA, it is being removed for the site.
> Remove Google Analytics tag

- content/millennium/r4/base/management/encounter.md
- lib/resources/example_json/r4_examples_encounter.rb
Description
----
added new example for R4 Encounter Retrieve by id
PR Checklist
----
> added new example for R4 Encounter Retrieve by id

- lib/resources/r4/communication.yaml
Description
----
R4 Communication only supports HL7 CommunicationCategory values of `notification` and `reminder` as well as SNOMED CT `312853008`. This update is to specify this restriction.
Current:
With changes:
PR Checklist
----
> R4 Communication add note for supported categories

- content/millennium/dstu2/general-clinical/condition.md
- lib/resources.rb
- lib/resources/dstu2/condition.yaml
- lib/resources/example_json/dstu2_examples_condition.rb
Description
----
Added meta.security to the condition response examples.
Added disclaimer for when meta.security is going to be populated.
Added meta.security to terminology bindings.
Screenshot before changes being merged:
Updated response and disclaimer:
Updated terminology binding:
PR Checklist
----
> Update dstu2 condition documentation by adding meta.security

- content/millennium/r4/clinical/summary/condition.md
- lib/resources.rb
- lib/resources/example_json/r4_examples_condition.rb
- lib/resources/r4/condition.yaml
Description
----
Added meta.security to the condition response examples.
Added disclaimer for when meta.security is going to be populated.
Added meta.security to terminology bindings.
Screenshot before changes being merged:
Updated terminology binding:
Updated response and disclaimer
PR Checklist
----
> Update r4 condition documentation by adding meta.security

- content/millennium/r4/financial/general/charge-item.md
- content/millennium/r4/proprietary-codes-and-systems.md
- lib/resources/r4/charge_item.yaml
Description
----
In preparation for migrating to Oracle docs, we are reviewing and correcting any inconsistencies, typos, broken links, etc. This PR aims to correct any of the above that needs to be addressed within ChargeItem and any other information directly referenced by it.
Within Chargeitem.extension[x].extension[x].valueCodeableConcept for procedure-codes anchor link is broken, it should be https://fhir.cerner.com/millennium/r4/financial/general/charge-item/#extension
**Before**:
**After**: 
When clicking Bill Code types for Chargeitem.extension[x].extension[x].valueCodeableConcept for procedure-codes, its corresponding bill type code PROCCODE is missing from the list of possible bill type codes. 
**Before**: 
**After**:
Chargeitem.extension[x].valueCodeableConcept for revenue-code …
> Review and corrections for ChargeItem

- content/millennium/r4/foundation/conformance/capability-statement.md
Description
----
In preparation for migrating to Oracle docs, we are reviewing and correcting any inconsistencies, typos, broken links, etc. This PR aims to correct any of the above that needs to be addressed within CapabilityStatement and any other information directly referenced by it. 
Small typo fix on /metadata implementation notes: 
Before: 
After:
PR Checklist
----
> typo fix for CapabilityStatement

- content/millennium/dstu2/care-provision/care-plan.md
Modify wording for clarity in DSTU2 Care Plan resource
Description
----
Single line change for the DSTU2 CarePlan Resource for wording.
We only have DSTU2 and R4, instead of anything on STU3 over here.
Otherwise, all links verified as good, and the rest of the DSTU2 resource itself looks fine.
PR Checklist
----
Current state - highlighted text being changed, as shown in the commits section.
Future state wording:
> Updated DSTU2 care-plan

- content/millennium/r4/clinical/care-provision/care-plan.md
Formatting updates to be consistent across parameter notes, including punctuation, and matching _revinclude to other parameters' styling.
Verified good links throughout document and have validated that example API calls behave as noted with examples.
Description
----
- Miscellaneous formatting changes (e.g. adding periods/punctuation) for consistency across parameters
- Parameters table - Required flag for _revinclude changed to match others'
- Parameter notes - _id changed wording to note interaction with _revinclude
- Parameter notes - _revinclude modified structure to largely match other parameters' styling
PR Checklist
----
- Parameters table before _revinclude change:
After:
- _id parameter details before change:
After:
- …
> Updated R4 CarePlan Resource

- content/millennium/r4/foundation/other/binary.md
General formatting updates.  
Itemized list follows on Pull Request's Description
Verified good links throughout document, and have validated that example API calls behave as noted with examples
Description
----
- Overview paragraph changed to indicate that the list of supported reports types is subject to change over time
- Formatting for a lot of untagged "code" elements/parameters by adding backticks
- Added links out to other R4 resources where referenced (e.g. DocumentReference and DiagnosticReport)
- Formatting updates in autogen-ccd-if section (e.g. properly spacing over the example GET command)
PR Checklist
----
- Overview paragraph before
- Overview paragraph after
- Resources w/o links
- Resources w/ links …
> Updated R4 Binary Resource

- content/millennium/r4/clinical/care-provision/care-team.md
Formatting updates to be consistent across parameter table and notes, including punctuation, and matching _revinclude to other parameters' styling.
Verified good links throughout document and have validated that example API calls behave as noted with examples.
Description
----
- Parameters table - Required flag for _revinclude changed to match others'
- Parameter notes - _revinclude modified structure to largely match other parameters' styling
PR Checklist
----
- Parameters table before _revinclude change:
- After:
-  _revinclude section of parameter notes before change:
- After:
> Updated R4 CareTeam Resource

- content/millennium/dstu2/infrastructure/binary.md
General formatting updates.  
Itemized list follows on Pull Request's Description
Verified good links throughout document, and have validated that example API calls behave as noted with examples
Description
----
- Overview paragraph changed to indicate that the list of supported reports types is subject to change over time
- Formatting for a lot of untagged "code" elements/parameters by adding backticks
- Added links out to other R4 resources where referenced (e.g. DocumentReference and DiagnosticReport)
PR Checklist
----
- Overview paragraph before
- Overview paragraph after
- Resources w/o links
- Resources w/ links
> Updated DSTU2 Binary Resource

- content/millennium/r4/financial/general/account.md
- lib/resources/example_json/r4_examples_account.rb
Description
----
Documentation for custom encounter search
PR Checklist
----
src="https://github.com/cerner/fhir.cerner.com/assets/33324957/1a1b2798-3c9c-42b4-94e7-2bbd9b49090b">
> Custom encounter search

- content/millennium/r4/base/entities/device.md
Description
----
In preparation for migrating to Oracle docs, we are reviewing and correcting any inconsistencies, typos, broken links, etc. This PR aims to correct any of the above that needs to be addressed within Consent/Contract and any other information directly referenced by it.
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
PR Checklist
----
> Review and Corrections for Device

- content/millennium/r4/base/workflow/appointment.md
- lib/resources/example_json/r4_examples_appointment.rb
- lib/resources/r4/appointment_patch.yaml
Description
----
Update the R4 Appointment resource for consistency and readability.
PR Checklist
----
Changes
----
Overview
before:
after:
Fields
before:
after:
**disclaimer and errors sentence were moved here and removed from each example**
Search parameters
before:
after (reordered, put field names as code, updated examples):
Search notes
before:
after:
Patch status
before:
after:
Patch video visit fields (common change on all fields)
before:
after:
> R4 Appointment updates

- content/millennium/r4/base/workflow/appointment.md
Description
----
Moved Patch below Create for consistency
PR Checklist
----
> Reorder actions to Search, Read, Create, Patch

- content/millennium/r4/base/workflow/slot.md
- lib/resources/example_json/r4_examples_slot.rb
Description
----
R4_UK_BRAM_Update_Slot_include
PR Checklist
----
> R4_UK_BRAM_Update_Slot_include

- content/millennium/r4/financial/general/account.md
- lib/resources/example_json/r4_examples_account.rb
- lib/resources/example_json/r4_examples_appointment.rb
- lib/resources/r4/appointment_patch.yaml
Description
----
Update action-comment in cancellation workflow and custom encounter search
PR Checklist
----
src="https://github.com/cerner/fhir.cerner.com/assets/33324957/32d85e8b-86a7-4894-a976-9850f69c424d">
> Update action-comment in cancellation workflow and custom encounter search

- content/millennium/dstu2/general-clinical/condition.md
- content/millennium/r4/clinical/summary/condition.md
- lib/resources/dstu2/condition.yaml
- lib/resources/example_json/r4_examples_condition.rb
- lib/resources/r4/condition.yaml
Description
----
In preparation for migrating to Oracle docs, we are reviewing and correcting any inconsistencies, typos, broken links, etc. This PR aims to correct any of the above that needs to be addressed within Consent/Contract and any other information directly referenced by it.
*click*
**After**
---
**Before**
*click*
**After**
---
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
PR Checklist
----
> Review and Corrections for Condition

- content/millennium/r4/foundation/documents/document-reference.md
- lib/resources/example_json/r4_examples_document_reference.rb
- lib/resources/r4/document_reference.yaml
Tons of formatting updates in this one, and substantial re-wording of sections to be more descriptive and in a similar style to other resources that were recently updated.
Description
----
- Backtick'd a lot of elements throughout the entire page, including some linked elements
- Overview paragraph updated
- Links to FHIR-controlled fields updated
- Custodian link wasn't pointing to r4 specifically - adjusted
- Per PR#349, the Document description/title link is no longer supported and needed removed
- https://github.com/cerner/fhir.cerner.com/pull/349
- Added links out to the R4 Binary resource in various places, since that resource gets referred to by this …
> Updated DocumentReference R4 Resource

- content/millennium/dstu2/diagnostic/diagnostic-report.md
Just a handful of formatting updates in this one, along with re-wording the opening paragraph to more closely match the R4 resource's styling.
Validated that API calls behave as expected with expected and unexpected parameters.
Description
----
- Updated Overview wording to more closely reflect the R4 resource.
- Moved Implementation Notes below the Parameters table, in line with other resources' formatting.
- Updated Parameters table formatting slightly.
- Added backticks to "required?" column for appropriate elements.
- Updated wording around the _count parameter's notes.
PR Checklist
----
Old Overview:
New Overview:
Old Parameters table + Implementation Notes …
> Updated DiagnosticReport DSTU2 Resource

- content/millennium/r4/clinical/diagnostics/diagnostic-report.md
- lib/resources/example_json/r4_examples_diagnostic_report.rb
This one needed several updates.
Verified good links throughout document and added some.
Description
----
- Reworded and expanded Overview paragraph
- Moved all shortname links to the end of the file, instead of following the Parameters section
- Linked to related resources where appropriate (e.g. out to Observation in the Overview)
- Parameters list corrected/adjusted.
- Category and Code in particular needed updated to match the resource's behavior (yaml file was up to date on behavior)
- _Revinclude parameter details adjusted, similar to other resources we've touched recently
- Several Example-related updates
- Header changes for clarity on which Example does what
- Patient search example changed and added the Ccategory parameter in request. Response structure has substantially more …
> Diagnostic report r4 docs migrate

- content/millennium/dstu2/encounters/encounter.md
- content/millennium/r4/base/management/encounter.md
- lib/resources/r4/encounter.yaml
Description
----
In preparation for migrating to Oracle docs, we are reviewing and correcting any inconsistencies, typos, broken links, etc. This PR aims to correct any of the above that needs to be addressed within Encounter and any other information directly referenced by it.
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
---
**Before**
*On clicking Encounter Priority details link*
**After**
PR Checklist
----
> Review and Updates for Encounter

- content/millennium/r4/base/entities/location.md
- lib/resources/example_json/r4_examples_location.rb
Description
----
In preparation for migrating to Oracle docs, we are reviewing and correcting any inconsistencies, typos, broken links, etc. This PR aims to correct any of the above that needs to be addressed within Consent/Contract and any other information directly referenced by it.
**Before**
**After**
---
**Before**
**After**
**Before**
**After**
PR Checklist
----
> Review and updates for Location

- content/millennium/r4/clinical/care-provision/nutrition-order.md
Description
----
In preparation for migrating to Oracle docs, we are reviewing and correcting any inconsistencies, typos, broken links, etc. This PR aims to correct any of the above that needs to be addressed within NutritionOrder and any other information directly referenced by it.
**Before**
**After**
---
**Before**
**After**
**Before**
!!! The duplicated chunk in question !!!
**After**
!!! Duplicated chunk is gone !!!
PR Checklist
----
> Review and Updates for NutritionOrder

- content/millennium/r4/clinical/diagnostics/diagnostic-report.md
- lib/resources/example_json/r4_examples_diagnostic_report.rb
- lib/resources/r4/diagnostic_report_create.yaml
Description
----
PR Checklist
----
> Diagnostic Report Create for Cardiology and Anatomic pathology

- content/millennium/r4/financial/general/insurance-plan.md
- lib/resources/example_json/r4_examples_insurance_plan.rb
Just a handful formatting updates in this one, and substantial re-wording of sections to be more descriptive and in a similar style to other resources that were recently updated.
Description
----
- Updated the overview paragraph a little
- Adjust The "Insurance Plan ID" link to actually point to the InsurancePlan's ID
- Added the base "ID" field as well
- Consolidated the Disclaimer, errors, and outcomes sections
- Updated the Parameters table and created the Implementation Notes section to assist developers in understanding what they can feed the system
- Updated a few examples - it looks like a bad find/replace was used, so we had some single quote …
> Updated InsurancePlan R4 Resource

- content/millennium/r4/clinical/medications/immunization.md
- lib/resources/r4/immunization.yaml
Had several changes on this one, including some re-wording of Overview and Implementation Notes sections to be more descriptive / in a similar style to other resources that were recently updated.
Description
----
- Re-did Overview paragraph.
- Matches what HL7.org has, and is in-line with the recent proposed DSTU2 formatting.
- Now includes direct links out to the `AllergyIntolerance` and `MedicationAdministration` resources.
- Switched links from http -> https for HL7.org in markdown and yaml files
- Modified link structure around the `Note` field, and referenced over to the `Annotation` formatting for R4.
- Switched to single disclaimer + errors/outcomes …
> Updated Immunization R4 Resource

- content/millennium/r4/clinical/summary/family-member-history.md
- lib/resources/r4/family_member_history.yaml
Description
----
In preparation for migrating to Oracle docs, we are reviewing and correcting any inconsistencies, typos, broken links, etc. This PR aims to correct any of the above that needs to be addressed within FamilyMemberHistory and any other information directly referenced by it.
**Before**
**After**
---
**Before**
leads to 
which link to nowhere
**After**
On click instead lead to appropriate fhir domainresource on modifiers and extensions
---
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
**Before**
**After**
---
**Before**
**After**
PR Checklist
----
> Review and Updates for FamilyMemberHistory

- content/millennium/r4/base/workflow/appointment.md
- lib/resources/example_json/r4_examples_appointment.rb
- lib/resources/r4/appointment_patch.yaml
Description
----
Documenting changes to the Reschedule Appointment Workflow
PR Checklist
----
> [Millennium-R4]: Reschedule Appointment Workflow Update

- content/millennium/dstu2/medications/medication-administration.md
Many formatting updates in this one, and substantial re-wording of sections to be more descriptive and in a similar style to other resources that were recently updated.
Description
----
- Rewriting of Overview, including link over to `Immunization` Resource.
- Condensed / removed duplicate "IMPORTANT NOTE" sections throughout document.
- Removed the "NOTE" section throughout the entire document about "these corrections may be breaking changes..."
- shouldn't be necessary at this time
- Removed a couple hidden <br/> characters
- Adjustments to Search Parameter Table and Implementation Notes sections.
- Matched currently approved formatting for the table.
- …
> Updated MedicationAdministration DSTU2 Resource

- content/millennium/dstu2/care-provision/goal.md
- content/millennium/r4/clinical/care-provision/goal.md
Description
----
In preparation for migrating to Oracle docs, we are reviewing and correcting any inconsistencies, typos, broken links, etc. This PR aims to correct any of the above that needs to be addressed within Communication and any other information directly referenced by it.
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
PR Checklist
----
> Review and Updates to Goal

- content/millennium/r4/clinical/request-and-response/communication.md
Description
----
In preparation for migrating to Oracle docs, we are reviewing and correcting any inconsistencies, typos, broken links, etc. This PR aims to correct any of the above that needs to be addressed within Communication and any other information directly referenced by it.
**Before**
**After**
**Before**
**After**
**Before**
**After**
*on scroll*
PR Checklist
----
> Review and Updates to Communication

- content/millennium/r4/base/individuals/practitioner.md
- lib/resources/example_json/r4_examples_practitioner.rb
- lib/resources/r4/practitioner.yaml
Description
----
* Removed extra search examples
* Changed 'id' to 'ID' throughout
* Fields
* Updated text
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/41f19d29-2d05-4ed7-84f6-6c331cab6422)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/e3fbfdd8-b8a8-4da8-aa77-1b6f04f46c74)
* Moved disclaimer and errors (see above)
* Extension
* Updated description
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/a65c417d-316f-40c8-9d67-b3e0ca2a7667)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/9fdfde2c-b6d4-41b5-bf49-c394242bf547)
* Search parameters
* Updated formatting and descriptions
* Updated notes
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/af33315d-4b5e-49fe-863b-13f66166fbe8)
* …
> R4 Practitioner updates

- content/millennium/dstu2/entities/person.md
- content/millennium/r4/base/individuals/person.md
- lib/resources/dstu2/person.yaml
- lib/resources/example_json/r4_examples_person.rb
- lib/resources/r4/person.yaml
Description
----
* Updated field list URLs to 'https'
* "id" -> "ID" throughout
* Field descriptions
* Updated info links to 'https'
* Moved disclaimer and errors to top
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/bc6307e6-d285-4a6a-952d-66ce42b1c95b)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/82e15500-ef25-4f63-8772-85753d4335ce)
* Updated Search params table format/descriptions
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/73f6d930-dae1-4e7d-ac91-c82e901cdbc9)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/372a428c-1de0-4afb-99ec-3b8bd5acec58)
* person-combine description
* Removed quotes
* Removed unsupported workflow statement 
* ![image](https://github.com/cerner/fhir.cerner.com/assets/2238 …
> Person updates for DSTU2 and R4

- content/millennium/dstu2/conformance/structure-definition.md
- content/millennium/r4/foundation/conformance/structure-definition.md
- lib/resources/example_json/dstu2_examples_structure_definition.rb
- lib/resources/example_json/r4_examples_structure_definition.rb
Description
----
* Removed example disclaimer
* Ensure example was updated and rubocop formatted
* Overview
* http links to https
* Update "id" to "ID"
* Reword second sentence
* <img width="590" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/22381097/544be03b-abdb-445d-abd6-b83938cb3d41">
* <img width="585" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/22381097/07910159-6828-4cff-93b1-9e2ff167de1a">
* Authorization Types
* Removed explicit type list
* <img width="240" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/22381097/82835738-bc5b-4fe6-b21d-146e205d83ff">
* <img width="231" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/22381097/e7a4084a-39bd-406f-8eae-ab8278c85c39">
* Ensure example was updated and …
> StructureDefinition updates

- content/millennium/dstu2/medications/medication-order.md
- lib/resources/dstu2/medication_order.yaml
Had various formatting changes on this one to get it into a similar style to other resources that were recently updated.
Verified/updated links throughout document.
Description
----
- Uppercasing and punctuation adds throughout document.
- Many links to HL7.org updated to use https.
- Also fixed dead links for ICD terminologies.
- Updated Overview Paragraph.
- Consolidated Disclaimer + Errors & Outcomes links.
- Clarified Custom Extension.
- Updated Parameter Table + Implementation Notes to match current standards, and behavior of the API.
PR Checklist
----
****************************
Old Overview:
New Overview:
****************************
Old Custom Extensions: …
> Updated Medication Order DSTU2 Resource

- content/millennium/dstu2/medications/medication-statement.md
- lib/resources/dstu2/contained_medication.yaml
- lib/resources/dstu2/medication_statement.yaml
- lib/resources/dstu2/medication_statement_contained_practitioner.yaml
Had a lot of formatting changes on this one to get it into a similar style to other resources that were recently updated.
Verified/updated links throughout document.
Description
----
- Updated Overview.  Reworded and re-spaced.
- Uppercasing and punctuation added in a lot of places. Some spacing changes too (e.g. leading spaces)
- Validated and/or fixed all existing links.  There were quite a few in this one.
- Added "info_link" to many lines in the yaml files
- Added link over to MedicationOrder in the relevant section
- Consolidated disclaimer + errors & outcomes notice
- Updated Custom Extensions for clarity
- Updated Parameter Table + Implementation Notes to match current standards
- Modified …
> Updated MedicationStatement DSTU2 Resource

- content/millennium/r4/clinical/medications/medication-request.md
- lib/resources/r4/medication_request.yaml
- lib/resources/r4/medication_request_contained_medication.yaml
Had a lot of formatting changes on this one to get it into a similar style to other resources that were recently updated.
Description
----
- Formatting changes throughout, including capitalizing/punctuation, and backticks to flip elements to code.
- Overview paragraph updated slightly.
- Condensed disclaimer to single instance.
- Overhauled Custom Extension section.
- Linked from the fields list. - Verified that anchor list changes were safe; no other pages in the repository reference this location at all).
- Re-formatted the common extensions into a table format (like they appear on most other resources).
- Swedish-specific extensions are still there, and …
> Updated MedicationRequest R4 Resource

- content/millennium/r4/foundation/security/provenance.md
- lib/resources/r4/provenance.yaml
Several formatting updates in this one, and re-wording of sections to be more descriptive and in a similar style to other resources that were recently updated.
Description
----
- Validated/updated all links out to HL7 websites.
- yaml file had a lot of examples of double forward-slashes
- Validated API behavior matches stated specifications.
- Updated Overview Paragraph.
- Uppercase'd returned fields list.
- Parameter Table and Implementation Notes updates to match current guidelines.
- Implementation Notes under the Create section modified to match current guidelines.
- Anonymized opc-request-id and X-Request-Id values added for response to Create section.
- Added backticks to quite a few …
> Updated Provenance R4 Resource

- content/millennium/dstu2/individuals/patient.md
- lib/resources/dstu2/patient.yaml
- lib/resources/example_json/dstu2_examples_patient.rb
- lib/resources/r4/patient.yaml
Description
----
Changes:
* "id" -> "ID" throughout
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/dcb6fe2e-50f6-40c1-bb45-1a8a9bc9cbe9)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/83ccf19d-6618-4357-9992-02071b095849)
* reference links updated to https
* search param table
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/facae51c-6d2c-4c0f-b117-2c7ca811aa44)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/7f8aa360-28df-4d73-a4f7-317f0841c6f0)
* search notes
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/052299f3-b67e-48ac-9745-864a2c76dbf7)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/d773fa2a-7079-46ab-b425-79b698fef50c)
PR Checklist
----
> DSTU 2 Patient updates

- lib/resources/example_json/r4_examples_document_reference.rb
- lib/resources/example_json/r4_examples_observation.rb
Description
----
Updated responses for R4 Observation and DocumentReference
PR Checklist
----
> R4 Observation,DocumentReference Documentation Updates

- content/millennium/r4/base/management/encounter.md
Description
----
Update R4 Encounter Sort details
PR Checklist
----
-
> R4 Encounter Period StartDateTime Sort Update

- content/millennium/r4/clinical/diagnostics/diagnostic-report.md
- content/millennium/r4/foundation/documents/document-reference.md
Description
----
[R4][DiagnosticReport][DocumentReference] support search by _lastUpdated
PR Checklist
----
> [R4][DiagnosticReport][DocumentReference] support search by _lastUpdated

- content/millennium/r4/clinical/medications/immunization.md
- content/millennium/r4/clinical/summary/allergy-intolerance.md
Description
----
[R4][AllergyIntolerance][Immunization] Support search by _lastUpdated
PR Checklist
----
> [R4][AllergyIntolerance][Immunization] Support search by _lastUpdated

- content/millennium/r4/clinical/summary/condition.md
- lib/resources/example_json/r4_examples_condition.rb
Description
----
PR Checklist
----
> [R4] Condition example updated with Diagnosis Type Extension

- content/millennium/r4/base/workflow/slot.md
Description
----
[R4][Slot] General Resource Extension update
PR Checklist
----
> [R4][Slot] General Resource Extension update

- content/millennium/r4/base/management/encounter.md
Description
----
[R4][Encounter] encounter.Class update
PR Checklist
----
> [R4][Encounter] encounter.Class update
