cerner/fhir.cerner.com

layouts/head.html
@dennispatterson / @daliboz - Please review
=> Add Google Analytics tracking to every page

content/dstu2/allergy-intolerance.md, content/dstu2/immunization.md, layouts/dstu2_sidebar.html, lib/resources.rb
Adding DSTU2 documentation for allergies and immunization
=> Add DSTU2 for allergies and immunization

content/dstu2/medication-prescription.md, layouts/dstu2_sidebar.html, lib/resources.rb
Adding updated MedicationPrescription doc for DSTU2
=> Add DSTU2 for MedicationPrescription

content/dstu2/diagnostic-report.md, layouts/dstu2_sidebar.html, lib/resources.rb
Add DSTU 2 documentation for DiagnosticReport
=> Add DSTU 2 documentation for DiagnosticReport

content/index.md, static/css/documentation.css
=> Add business request form to fhir.cerner.com

content/dstu2.md, content/dstu2/Authorization.md, layouts/dstu2_sidebar.html
Creating this pull request as an internal github review for the authorization documentation.
=> Initial commit of the authorization client-facing documentation

content/may2015/allergy-intolerance.md, lib/resources.rb
Updated params. Added a required field (will be pushing this through to other resources). Thoughts on doing this this way?
Updated examples.
=> update allergyIntolerance with new status param, new examples

content/may2015/condition.md, lib/resources.rb
Updated Condition with new params and response examples, updated to indicate which fields are required.
=> Update Condition with new params and response examples

content/may2015.md, lib/resources.rb
Updated open endpoint URLs with new domain name and updated metadata self url.
=> Updated open endpoint URLs

content/may2015/immunization.md, lib/resources.rb
New required param field and new response fields, include examples of both refused and actual immunizations
=> Update immunization with required param doc and new response fields

content/may2015/encounter.md, lib/resources.rb
Updates for May response fields and new parameters that were supported with the release.
=> Update Encounter with new response and parameters

content/may2015/diagnostic-report.md, lib/resources.rb
Updates for the new May 2015 response fields and required parameter documentation
=> Update DiagnosticReport documentation and response

content/may2015/medication-prescription.md, lib/resources.rb
Updates for MedicationPrescription based on the new fields and responses.
=> Add MedicationPrescription updates for May 2015 deployment

content/may2015/observation.md, lib/resources.rb
Add additional parameters for Observation, update response example with new fields and paging
=> Update Observation for May DSTU ballot

content/may2015/patient.md, lib/resources.rb
Updated patient with required parameter information, newer response examples
=> Update patient with May2015 response

content/may2015/authorization.md
Change link from Google groups to Cerner web form
=> Update 'contact us' link in the Authorization page

Rules, content/dstu2.md, content/dstu2/authorization.md, content/dstu2/conformance.md, layouts/dstu2_api.html, layouts/dstu2_sidebar.html, layouts/header.html, lib/dstu2_resources.rb, nanoc.yaml, static/css/documentation.css
Add the DSTU2 layout and placeholders
=> Updating for DSTU2 documentation

content/dstu2/patient.md, layouts/dstu2_sidebar.html, lib/dstu2_resources.rb
Adding documentation for Patient DSTU2
=> Adding Patient DSTU2 documentation

content/dstu2/medication-order.md, layouts/dstu2_sidebar.html, lib/dstu2_resources.rb
Adding documentation for MedicationOrder DSTU2
=> Adding MedicationOrder DSTU2 documentation

content/may2015/diagnostic-report.md
Updated DiagnosticReport with new date param
=> Update DiagnosticReport with new date parameter

content/dstu2/allergy-intolerance.md, content/dstu2/document-reference.md, content/may2015/document-reference.md, lib/definition_table_generator.rb, lib/resources/dstu2/allergy_intolerance.yaml, lib/resources/dstu2/document_reference.yaml, lib/resources/may2015/document_reference.yaml, lib/terminology_table.erb
Adding terminology table for supported terminologies of "Example" binding strength
=> Adding support for terminology binding table

content/dstu2/condition.md, lib/resources/dstu2/condition.yaml
Adding terminology table for condition resource
=> Add terminology bindings to DSTU 2 documentation for Condition resource.

content/dstu2/authorization.md
Removed sensitive information for the existing 1.1 version of the authorization server
=> Removed sensitive information

content/dstu2/observation.md, lib/dstu2_resources.rb
* Reorganize markdown links in observation.md
* Document the new 'component-code' query parameter
* Update description for 'date' query parameter
* Update DSTU2 Observations example for blood pressure components instead of contained
=> Update DSTU2 documentation for Observation

content/dstu2/medication-statement.md, lib/resources/dstu2/contained_medication.yaml, lib/resources/dstu2/medication_statement.yaml
- Update body fields for create and update
- Re-order fields to match resource
- Add contained Medication information
=> Update DSTU 2 documentation for Medication Statement.

content/dstu2/medication-order.md, lib/dstu2_resources.rb, lib/resources/dstu2/contained_medication.yaml, lib/resources/dstu2/medication_order.yaml
- Update supported search parameters
- Add terminology bindings
- Add note that contained Medications may be returned.
=> Update DSTU 2 documentation for Medication Order.

lib/dstu2_resources.rb, lib/resources/dstu2/immunization.yaml
- Updated terminology bindings
- Updated example bundle
=> Update DSTU 2 documentation for Immunization.

content/dstu2/document-reference.md, content/dstu2/patient.md, content/may2015/document-reference.md, lib/dstu2_resources.rb, lib/resources/dstu2/patient.yaml, lib/resources/dstu2/types.yaml
* Added terminology bindings.
* Added implementation notes that Is-Modifier fields of animal and link are not supported.
* Updated response.
=> Update DSTU2 documentation for Patient

content/dstu2/encounter.md, lib/dstu2_resources.rb, lib/resources/dstu2/encounter.yaml, lib/resources/dstu2/encounter_contained_location.yaml, lib/resources/dstu2/types.yaml
* Added terminology bindings.
* Added implementation notes that location.location and hospitalization.destination will reference contained location resources.
* Updated response.
=> Update DSTU2 documentation for Encounter

content/dstu2.md, content/dstu2/authorization.md, content/may2015.md, content/may2015/authorization.md
* Updated reference to ehr source to just differentiate URLs change by tenant since this will be changing/can vary more than what's documented.
* Brought May and DSTU 2 authorization documentation up to date (there was some variation that doesn't actually exist)
* Added section about wildcard scopes to clarify that they aren't supported
=> Clarify tenant terminology and wildcard scopes

content/dstu2/condition.md, lib/dstu2_resources.rb, lib/resources/dstu2/condition.yaml, lib/terminology_table.erb
Updated documentation for DSTU2 uplift on Condition Resource.
**Changes:**
- Added support for category code <code>problem</code> from argonaut extension codes system.
- Added back support for clinicalStatus.
- Updated related search sets and create and update requests with clinical status and category.
=>  Update DSTU2 documentation for Condition Resource.

content/dstu2/diagnostic-report.md, lib/dstu2_resources.rb, lib/resources/dstu2/diagnostic_report.yaml
* Added terminology binding for DiagnosticReport.category
* Added documentation for `date` and `_count` search parameters
* Updated example response to reflect current implementation
=> Update DSTU2 documentation for DiagnosticReport

content/dstu2.md, content/dstu2/allergy-intolerance.md, content/dstu2/condition.md, content/dstu2/document-reference.md, content/dstu2/medication-statement.md, content/may2015.md, content/may2015/document-reference.md, content/may2015/medication-statement.md, lib/resources.rb, lib/resources/example_json/dstu2_examples_allergy_intolerance.rb, lib/resources/example_json/dstu2_examples_appointment.rb, lib/resources/example_json/dstu2_examples_condition.rb, lib/resources/example_json/dstu2_examples_conformance.rb, lib/resources/example_json/dstu2_examples_device.rb, lib/resources/example_json/dstu2_examples_diagnostic_report.rb, lib/resources/example_json/dstu2_examples_encounter.rb, lib/resources/example_json/dstu2_examples_immunization.rb, lib/resources/example_json/dstu2_examples_medication_order.rb, lib/resources/example_json/dstu2_examples_medication_statement.rb, lib/resources/example_json/dstu2_examples_observation.rb, lib/resources/example_json/dstu2_examples_patient.rb
I've made these changes by find/replacing occurrences of "sandboxcernerpowerchart" with "sandboxcerner".  Please feel free to double check in case I missed any :)
=> Update FHIR server URLs

content/dstu2/goal.md, layouts/dstu2_sidebar.html, lib/resources/dstu2/goal.yaml, lib/resources/example_json/dstu2_examples_conformance.rb, lib/resources/example_json/dstu2_examples_goal.rb
Added DSTU2 documentation for Goals.
Spec: http://hl7.org/fhir/goal.html
=> Adding DSTU2 documentation for Goals

content/dstu2/authorization-specification.md, content/dstu2/authorization.md, content/dstu2/openid-connect.md
Updates to authorization documentation guidance and specification, including deep-dive on OpenID Connect.
=> Updates to authorization documentation guidance and specification

content/dstu2/authorization.md
Updating registration process for confidential clients.
=> Clarify confidential client registration

content/dstu2/observation.md, lib/resources/example_json/dstu2_examples_observation.rb
* Remove component-code parameter
* General tweaks for clarity
=> Update Observation documentation:

content/dstu2/patient.md
Adding the new parameters supported for searching patients.
=> Updating patient search

README.md
Updating the README to include documentation on the terminology_table helper method
=> Updating README.md with terminology_table documentation

content/millennium/dstu2/care-provision/care-plan.md, content/millennium/dstu2/care-provision/goal.md, content/millennium/dstu2/conformance.md, content/millennium/dstu2/devices/device.md, content/millennium/dstu2/diagnostic/diagnostic-report.md, content/millennium/dstu2/diagnostic/observation.md, content/millennium/dstu2/encounters/encounter.md, content/millennium/dstu2/entities/contract.md, content/millennium/dstu2/entities/person.md, content/millennium/dstu2/general-clinical/allergy-intolerance.md, content/millennium/dstu2/general-clinical/condition.md, content/millennium/dstu2/general-clinical/procedure.md, content/millennium/dstu2/individuals/patient.md, content/millennium/dstu2/individuals/related-person.md, content/millennium/dstu2/infrastructure/binary.md, content/millennium/dstu2/infrastructure/document-reference.md, content/millennium/dstu2/medications/immunization.md, content/millennium/dstu2/medications/medication-order.md, content/millennium/dstu2/medications/medication-statement.md, content/millennium/dstu2/operation-definition.md, content/millennium/dstu2/scheduling/appointment.md, lib/resources.rb
Apply the common template to the Patient resource, and add the Authorization types supported per action
=> Apply template to Patient, add authorization types

content/millennium/dstu2/medications/medication-statement.md, lib/resources/example_json/dstu2_examples_medication_statement.rb
Applied the new template to medication statement. This includes:
* Template changes
* Documenting authentication types
* Documenting by id queries
* Documenting custom extensions.
* Overview
* Instructions to query for "active"
=> Medication Statement template

content/millennium/dstu2/medications/medication-order.md
Updates MedicationOrder page to include authorization header for each action.
=> Add authorization header to MedicationOrder actions

static/css/documentation.css
Accidentally pulled too much CSS from the last changes. Still need the superscript styling.
=> Revert superscript change

content/soarian/dstu2/devices.md, content/soarian/dstu2/devices/device.md, content/soarian/dstu2/general-clinical.md, content/soarian/dstu2/general-clinical/allergy-intolerance.md, content/soarian/dstu2/individuals.md, content/soarian/dstu2/individuals/patient.md, content/soarian/dstu2/medications.md, content/soarian/dstu2/medications/medication-statement.md, layouts/soarian_dstu2_sidebar.html, lib/resources/dstu2/soarian_allergy_intolerance.yaml, lib/resources/dstu2/soarian_condition.yaml, lib/resources/dstu2/soarian_contained_medication.yaml, lib/resources/dstu2/soarian_device.yaml, lib/resources/dstu2/soarian_diagnostic_report.yaml, lib/resources/dstu2/soarian_patient.yaml, lib/resources/example_json/soarian_examples_allergy_intolerance.rb, lib/resources/example_json/soarian_examples_device.rb, lib/resources/example_json/soarian_examples_medication_statement.rb, lib/resources/example_json/soarian_examples_patient.rb, lib/terminology_table.erb
Updated slide bar to include AllergyIntolerance, Patient, MedicationStatement and Device resources.
Extension has been added for Patient and MedicationStatement resource.
Informational message added for device resource.
Incorporated the same changes which mentioned for Condition and DiagnosticReport resource.
=> Included AllergyIntolerance, Patient, MedicationStatement and Device resources.

content/millennium/dstu2/devices/device.md, content/millennium/dstu2/general-clinical/condition.md, content/millennium/dstu2/individuals/patient.md, content/millennium/dstu2/medications/medication-statement.md, lib/resources/dstu2/device.yaml
Apply the new template to the Device resource, add details about extensions and authorization types accepted.
=> Apply template to Millennium Device

content/smart.md, layouts/header.html, layouts/smart.html
Please review the initial SMART documentation.
@kpshek 
@mjhenkes 
@daliboz 
@torresdrew 
@shriniketsarkar 
@zplata
=> SMART documentation

content/millennium/dstu2/devices/device.md, content/millennium/dstu2/medications/immunization.md, lib/resources/dstu2/immunization.yaml
Apply template to Millennium Immunizations and add auth types.
Also corrected the device lot number to be more consistent while I was in here.
=> Immunization template

content/millennium/dstu2/medications/medication-order.md, lib/resources/dstu2/contained_medication.yaml, lib/resources/dstu2/medication_order.yaml
Applied new template to the MedicationOrder resource
=> Apply template to MedicationOrder

content/millennium/dstu2/individuals.md, content/millennium/dstu2/individuals/patient.md, content/millennium/dstu2/individuals/practitioner.md, layouts/millennium_dstu2_sidebar.html, lib/resources/dstu2/practitioner.yaml, lib/resources/example_json/dstu2_examples_practitioner.rb
Adds Practitioner resource.
Patient will be added to the Authorization Types header when Patient Access is available for Practitioner.
=> Add DSTU2 documentation for Practitioner resource

content/authorization.md, content/millennium/dstu2.md
Clarify that system account/b2b access is available only in sandbox, and steps used to register a b2b or offline access account
=> Clarified system account registration and limits

content/millennium/dstu2/general-clinical/procedure.md, lib/resources/dstu2/procedure.yaml
Apply template to Millennium Procedure, add auth types
=> Apply template to Millennium Procedure, add auth types

content/millennium/dstu2/infrastructure/document-reference.md, lib/resources/dstu2/document_reference.yaml, lib/resources/dstu2/document_reference_docref.yaml, lib/resources/example_json/dstu2_examples_document_reference.rb
Applied the template to Millennium DocumentReference, minor cleanup, and added auth type support
=> Apply template to Millennium DocumentReference and add auth type

content/millennium/dstu2/diagnostic/observation.md, lib/resources/dstu2/observation.yaml, lib/resources/example_json/dstu2_examples_observation.rb
Add authorization doc to Millennium Observation, add category parameter, apply template
=> Apply template to Millennium Observation and add category parameter

content/millennium/dstu2/general-clinical/allergy-intolerance.md, lib/resources/dstu2/allergy_intolerance.yaml
Updated to the new template, added authorization documentation
=> Update Millennium AllergyIntolerance to new template, add auth

content/millennium/dstu2/individuals/related-person.md, lib/resources/dstu2/related_person.yaml
Added supported authentication and applied template to Millennium RelatedPerson
=> Add auth types and template to Millennium RelatedPerson

content/millennium/dstu2/entities/person.md, lib/resources/dstu2/person.yaml
Changes to Millennium Person:
* Added auth types accepted
* Applied template
=> Added auth and applied template to Millennium Person

content/millennium/dstu2/encounters/encounter.md, content/millennium/dstu2/medications/immunization.md, lib/resources/dstu2/encounter.yaml, lib/resources/dstu2/encounter_contained_location.yaml
* Applied the official template to the Millennium Encounter resource
* Fixed some Immunization links I noticed went to latest instead of dstu2
=> Apply template to encounter, fix links in Immunization

content/millennium/dstu2/entities/contract.md, lib/resources/dstu2/contract.yaml
Update millennium contract overview, apply template and add auth accepted
=> Update millennium contract with template

content/millennium/dstu2/infrastructure/binary.md
Added accepted auth types and applied the template to the Binary resource. 
This one is a bit tricky. Please review the documentation adjustments and examples to ensure they're clear and correct.
=> Add auth types, apply template to Millennium Binary

content/millennium/dstu2/diagnostic/observation.md
_lastUpdated will be a supported search parameter for Observations.
=> Adding _lastUpdated as a search parameter for Observation

lib/resources/example_json/dstu2_examples_observation.rb
The intermediary 'form' social history is no longer displayed, and the value of the social history is its assessment.
=> Update Observation example to reflect flattened social history structure

content/smart.md
I'd like some feedback on the following additions.
@kpshek 
@daliboz 
@whitehatguy 
@mjhenkes 
@shriniketsarkar 
@zplata
=> Add information about the embedded browser to SMART doc

content/millennium/dstu2/diagnostic/observation.md
One clarification for the lastUpdated parameter
=> Minor update to _lastUpdated parameter in Millennium Observation

content/smart.md
Add information about no custom port usage when testing in PowerChart
@ericsornson 
@kpshek 
@mjhenkes 
@zplata 
@shriniketsarkar
=> Add info about custom port usage

content/millennium/dstu2/individuals/practitioner.md
Adds Patient to Practitioner resource authorization types.
=> OPENSVC-1550: Add patient to Practitioner authorization types

content/millennium/dstu2/general-clinical/allergy-intolerance.md, content/millennium/dstu2/general-clinical/condition.md
Adds notes to AllergyIntolerance.note and Condition.notes.
=> Update AllergyIntolerance and Condition Note

Rules, layouts/header.html, lib/helpers/attributes_helper.rb, static/css/documentation.css
To provide more visibility to the Code Portal, a prominent button is displayed on the Millennium, Authorization, and SMART sections of the fhir.cerner.com site.
=> Added Code Portal Button

content/millennium/dstu2/scheduling.md, content/millennium/dstu2/scheduling/appointment.md, content/millennium/dstu2/scheduling/schedule.md, content/millennium/dstu2/scheduling/slot.md, layouts/millennium_dstu2_sidebar.html, lib/resources/dstu2/appointment.yaml, lib/resources/dstu2/schedule.yaml, lib/resources/dstu2/slot.yaml, lib/resources/example_json/dstu2_examples_appointment.rb, lib/resources/example_json/dstu2_examples_schedule.rb, lib/resources/example_json/dstu2_examples_slot.rb
Adds Schedule and Slot resources.
Updates Appointment resource to include create operation.
**Note:**
Should not be merged until these resources are released.
=> Add DSTU2 documentation for Schedule, Slot and Appointment write.

content/millennium/dstu2/scheduling/appointment.md, content/millennium/dstu2/scheduling/schedule.md, content/millennium/dstu2/scheduling/slot.md, lib/resources/dstu2/appointment.yaml, lib/resources/example_json/dstu2_examples_appointment.rb, lib/resources/example_json/dstu2_examples_schedule.rb, lib/resources/example_json/dstu2_examples_slot.rb
Updating the documentation for the Appointment, Slot, and Schedule resources for a slew of issues including: 
- incorrect search parameter
- example responses from the wrong environments
- unhelpful example ids
- unhelpful example querys
- misleading overview documentation
=> Scheduling resource updates

content/authorization.md
=> OAuth 2.0 for Native Apps has moved from draft to final RFC

content/millennium/dstu2/care-provision/care-plan.md, content/millennium/dstu2/diagnostic/observation.md, content/millennium/dstu2/medications/medication-statement.md, lib/resources/dstu2/care_plan.yaml, lib/resources/example_json/dstu2_examples_care_plan.rb
Apply templates and authorization to careplan
Minor cleanup of a few other links/text.
=> Careplan auth

content/millennium/dstu2/care-provision/goal.md, lib/resources/dstu2/goal.yaml, lib/resources/example_json/dstu2_examples_goal.rb
Add authentication do and apply the template to goal doc
=> Apply Auth and template to goal doc

content/millennium/dstu2/operation-definition.md, lib/resources/example_json/dstu2_examples_care_plan.rb
Applied the template to the OperationDefinition resource
=> Apply template and auth details to OperationDefinition

content/soarian/dstu2.md
Modified Soarian overview page
=> Modified Soarian overview page

Gemfile, Gemfile.lock
=> yajl-ruby 1.2.1 -> 1.3.1 (fixes #178)

content/millennium/dstu2/entities/person.md, lib/resources/example_json/dstu2_examples_person.rb
Updating the Person resource to address upcoming person combine behavior similar to the Patient resource.
=> Documentation for Person combines

content/millennium/dstu2/medications.md, content/millennium/dstu2/medications/medication-administration.md, layouts/millennium_dstu2_sidebar.html, lib/resources/example_json/dstu2_examples_medication_administration.rb
Adds the MedicationAdministration resource documentation.
Example returns will be updated with real data from fake FHIRPLAY patients.
=> Add DSTU2 Documentation for MedicationAdministration resource

content/millennium/dstu2.md, content/millennium/faq/common-issues.md, content/smart.md, layouts/highlights.html, layouts/millennium_faq_sidebar.html
To provide better documentation on common issues experienced by app developers we'd like to include the following common issues documentation in the FAQ section of fhir.cerner.com.
=> Document common issues

content/millennium/dstu2/infrastructure/document-reference.md, lib/resources/dstu2/document_reference.yaml, lib/resources/example_json/dstu2_examples_document_reference.rb
Updates the DocumentReference resource for upcoming search functionality.
Also adds a note to one of the DocumentReference create fields describing an additional requirement around meta tags.
=> Documentation for DocumentReference Search

content/authorization/authorization-specification.md
Support for multiple redirect URIs was recently introduced
=> Fixed minor typo/word choice and corrected small inaccuracy around redirect URIs

lib/resources/dstu2/document_reference.yaml
Clarifying what the value set is and how to get more codes mapped.
=> Millennium DocumentReference.type clarifications

content/millennium/dstu2/diagnostic/diagnostic-report.md, lib/resources/dstu2/diagnostic_report.yaml
Added the template to DiagnosticReport, overview, and some clarifications.
=> Add auth and clarify DiagnosticReport capabilities for Millennium

content/millennium/dstu2/medications/medication-order.md
Adds Patient to Medication Order resource authorization types.
=> Add patient authorization to medication order

content/millennium/dstu2/medications/medication-order.md
Adds _lastUpdated to params section.  Also adds a notes section to describe _lastUpdated parameter requirements.
=> Add Documentation for MedicationOrder _lastUpdated Parameter

content/millennium/dstu2.md, content/millennium/dstu2/care-provision/care-plan.md, content/millennium/dstu2/care-provision/goal.md, content/millennium/dstu2/devices/device.md, content/millennium/dstu2/diagnostic/diagnostic-report.md, content/millennium/dstu2/diagnostic/observation.md, content/millennium/dstu2/encounters/encounter.md, content/millennium/dstu2/entities/contract.md, content/millennium/dstu2/entities/person.md, content/millennium/dstu2/general-clinical/allergy-intolerance.md, content/millennium/dstu2/general-clinical/condition.md, content/millennium/dstu2/general-clinical/procedure.md, content/millennium/dstu2/individuals/patient.md, content/millennium/dstu2/individuals/practitioner.md, content/millennium/dstu2/individuals/related-person.md, content/millennium/dstu2/infrastructure/binary.md, content/millennium/dstu2/infrastructure/document-reference.md, content/millennium/dstu2/medications/immunization.md, content/millennium/dstu2/medications/medication-administration.md, content/millennium/dstu2/medications/medication-order.md, content/millennium/dstu2/medications/medication-statement.md, content/millennium/dstu2/scheduling/appointment.md, content/millennium/dstu2/scheduling/schedule.md, content/millennium/dstu2/scheduling/slot.md
Adds section to overview describing when OperationOutcomes and DARs are returned.  Also provides a few simple examples.
=> Add Handling Required Fields section to overview

content/millennium/dstu2/scheduling/appointment.md, lib/resources/dstu2/appointment.yaml, lib/resources/example_json/dstu2_examples_appointment.rb
Updates Appointment resource to include update operation.
=> Add DSTU2 documentation for Appointment status update

content/smart.md
Add Terra UI, SMART apps in MPages, and P3P sections
=> Add Terra UI, SMART apps in MPages, and P3P sections

content/authorization.md, content/authorization/authorization-specification.md, content/millennium/dstu2/medications/medication-statement.md
8ab03db
Add implementation notes for MedicationStatement create and update
6e3491b
Remove a few other references to wildcard scopes
=> MedicationStatement and wildcard scope changes

content/millennium/dstu2/scheduling/slot.md, lib/resources/example_json/dstu2_examples_slot.rb
adding documentation for slot search proprietary codes
- new slot type search param using  proprietary codes
- update output response which includes proprietary codes
=> Slot proprietary codes

content/millennium/dstu2/general-clinical/allergy-intolerance.md
Just moving this to use closed endpoint since writes with open endpoint will 404
=> AllergyIntolerance Create uses closed endpoint

lib/resources/example_json/dstu2_examples_appointment.rb
Update Appointment examples to reflect return of proprietary codes.
=> Update Appointment examples to reflect return of proprietary codes.

content/millennium/r4/encounters/encounter.md, lib/resources/example_json/r4_examples_encounter.rb, lib/resources/r4/encounter.yaml
Not to be merged until after https://github.com/cerner/fhir.cerner.com/pull/238 is in master.
=>  Add Documentation for R4 Encounter Write 

content/millennium/r4/individuals/patient.md, lib/definition_table_generator.rb, lib/patch_definition_table.erb, lib/resources/example_json/r4_examples_patient.rb, lib/resources/r4/patient.yaml, lib/resources/r4/patient_patch.yaml, lib/resources/r4/types.yaml
Adds R4 documentation for Patient Patch capability.
=> [R4] Add documentation for Patient Patch capability

content/millennium/r4/encounters/encounter.md, lib/resources.rb, lib/resources/example_json/r4_examples_encounter.rb, lib/resources/r4/encounter.yaml, lib/resources/r4/encounter_patch.yaml
Adding documentation for encounter patch.
Please review commit: 6e42f74
=> Add documentation for Encounter patch.

content/millennium/r4/individuals/patient.md, lib/resources/example_json/r4_examples_patient.rb
The Patient Combines Example needs to be updated.
=> Updating Patient Combines Example

content/authorization.md, layouts/header.html
Updated our references to System Accounts and put directions on how to fill out fields in our doc. Tried to clarify why we use this.
Also updated references to code Console to be more consistent throughout @kolkheang 
@mbeerman make sure my wording and updates make sense for the way Cerner Central works if My Domain is active/the updates to doc look as you would expect.
=> Update system accounts registration

content/soarian/dstu2.md, content/soarian/dstu2/care-provision/careplan.md, content/soarian/dstu2/diagnostic/diagnostic-report.md, content/soarian/dstu2/diagnostic/observation.md, lib/resources/example_json/soarian_examples_care_plan.rb, lib/resources/example_json/soarian_examples_diagnostic_report.rb, lib/resources/example_json/soarian_examples_fhir_link.rb, lib/resources/example_json/soarian_examples_link_extension.rb, lib/resources/example_json/soarian_examples_observation.rb
Included secure sandbox endpoint url and pagination changes for Observation, CarePlan and Diagnostic Report resource
=> Secure sandbox endpoint url and pagination.

content/millennium/r4/general-clinical.md, content/millennium/r4/general-clinical/allergy-intolerance.md, layouts/general-clinical.html, layouts/millennium_r4_sidebar.html, lib/resources/example_json/r4_examples_allergy_intolerance.rb, lib/resources/r4/allergy_intolerance.yaml
Contains all the documentation to explain AllergyIntolerance Read and Search
=> R4 AllergyIntolerance Read/Search

lib/resources/r4/allergy_intolerance.yaml
Fixing the link for the AllergyIntolerance VerificationStatus ValueSet link
=> Fix AllergyIntolerance VerificationStatus ValueSet link

lib/resources/dstu2/allergy_intolerance.yaml, lib/resources/example_json/dstu2_examples_allergy_intolerance.rb
0291874 reformats the example JSON
5951e27 changes the contained RelatedPerson in the AllergyIntolerance update JSON to a contained Practitioner
cf49179 updates a few JSON errors in yaml examples and splits single example sections with two entries into two example sections
=> DSTU2 allergy fixes

content/millennium/r4/scheduling/appointment.md, lib/resources/example_json/r4_examples_appointment.rb, lib/resources/r4/appointment.yaml
Added documentation for R4 Appointment Write
=> R4 Appointment write

content/millennium/r4.md, content/millennium/r4/general-clinical.md, content/millennium/r4/general-clinical/condition.md, content/millennium/r4/proprietary-codes.md, layouts/millennium_r4_sidebar.html, lib/resources/example_json/r4_examples_condition.rb, lib/resources/r4/condition.yaml
Adding documentation for R4 Condition (Problem) Search.
=> Add documentation for R4 Condition (Problem) Search.

lib/resources/example_json/r4_examples_patient.rb
Practitioner 995932 became inactive. Updating to an active Practitioner.
=> Update R4 Patient Create example for generalPractitioner

content/millennium/dstu2/medications/immunization.md, content/millennium/r4/medications.md, content/millennium/r4/medications/immunization.md, content/millennium/r4/proprietary-codes.md, layouts/medications_r4.html, layouts/millennium_r4_sidebar.html, lib/resources/example_json/r4_examples_immunization.rb, lib/resources/r4/immunization.yaml
Added documentation for R4 Immunization read and search features
=> Documentation for R4 Immunization Read and Search

content/millennium/dstu2/diagnostic/observation.md
New content is L48 - L52
Other changes in the file are formatting
=> Document default sort behavior for Observations

content/millennium/r4/general-clinical/condition.md, lib/resources/example_json/r4_examples_condition.rb, lib/resources/r4/condition.yaml
This PR is same as this(https://github.com/cerner/fhir.cerner.com/pull/281). We are unable to merge the first one as it was from a forked repository. And directly merging the current PR as the code was already reviewed.
=> Documentation for Condition Update.

content/authorization.md
LN 97 is where the actual change is. The other changes are from my editor removing white spaces.
=> Make system account URL a link

lib/resources/example_json/r4_examples_relatedperson.rb
Change name and communication of Related Person to array in R4_examples
=> Change name and communication of Related Person to array in R4_examples

lib/resources/r4/account.yaml
StructureDefinition: State description updated.
=> Account structure definitions extensions updates

content/millennium/dstu2.md, content/millennium/r4.md, lib/resources.rb
=> Add Data Concurrency Documentation

content/millennium/r4.md, content/millennium/r4/general-clinical.md, content/millennium/r4/general-clinical/procedure.md, content/millennium/r4/proprietary-codes-and-systems.md, layouts/millennium_r4_sidebar.html, lib/resources/example_json/r4_examples_procedure.rb, lib/resources/r4/procedure.yaml
Adding documentation for R4 Procedure Read and Search.
=> Add documentation for R4 Procedure Read/Search.

content/millennium/r4/general-clinical/allergy-intolerance.md, lib/resources/example_json/r4_examples_allergy_intolerance.rb, lib/resources/r4/allergy_intolerance.yaml
**Changes**:
- Added New fields - Encounter, Severity
- Added Terminology Binding for Severity
- Removed duplicate terminology binding for Criticality
- Update to the URL's to secured
- Updated field names to Capitalize
=> Update documentation for R4 Allergy Read,Searches

content/millennium/dstu2/conformance.md, content/millennium/dstu2/structure-definition.md
These changes only relate to resources in the Overview group. The goal of this PR is to let the user know that the JSON data from the example requests in a few of the examples are likely to change. Also, full paths were added to the conformance examples.
There will be more similar changes coming for the other resources (most likely much larger since there are some larger inconsistencies).
=> Overview Resources JSON Inconsistencies

content/millennium/r4/general-clinical/allergy-intolerance.md, lib/resources/example_json/r4_examples_allergy_intolerance.rb, lib/resources/r4/allergy_intolerance.yaml
Documentation for R4 AllergyIntolerance Writes.
=> AllergyIntolerance r4 write documentation

content/millennium/dstu2/conformance.md, content/millennium/dstu2/conformance/conformance.md, content/millennium/dstu2/conformance/operation-definition.md, content/millennium/dstu2/conformance/structure-definition.md, content/millennium/r4/conformance.md, content/millennium/r4/conformance/capability-statement.md, content/millennium/r4/conformance/structure-definition.md, layouts/conformance.html, layouts/millennium_dstu2_sidebar.html, layouts/millennium_r4_sidebar.html, lib/resources/example_json/r4_examples_structure_definition.rb, nanoc.yaml
Added Structure Definition Page for R4
=> Added R4 Structure Definition Page

content/millennium/r4/entities.md, content/millennium/r4/entities/organization.md, content/millennium/r4/proprietary-codes-and-systems.md, layouts/entities.html, layouts/millennium_r4_sidebar.html, lib/resources/example_json/r4_examples_organization.rb, lib/resources/r4/allergy_intolerance.yaml, lib/resources/r4/organization.yaml
Adding documentation for R4 Organization Read and Search.
=> Add Documentation for R4 Organization Read and Searches

content/millennium/r4/entities/organization.md, lib/resources/example_json/r4_examples_organization.rb, lib/resources/r4/organization.yaml
Added Documentation for R4 Organization Writes
=> Add Documentation R4 Organization Writes

README.md, content/millennium/r4/individuals/practitioner.md, lib/resources/example_json/r4_examples_practitioner.rb, lib/resources/r4/patient.yaml, lib/resources/r4/practitioner.yaml
=> Documentation for R4 Practitioner Create

content/millennium/r4/individuals/practitioner.md
=> Update documentation for Practitioner search

lib/resources/r4/encounter.yaml
=> Add Encounter External Indicator Documentation

lib/resources/example_json/r4_examples_encounter.rb, lib/resources/r4/encounter.yaml
Update documentation for R4 Encounter creates to remove locations, location.location fields and add serviceProvider as required field.
=> R4 - Update Encounter write fields

content/millennium/r4/medications/immunization.md, lib/resources/example_json/r4_examples_immunization.rb, lib/resources/r4/immunization.yaml
Adding Documentation for Immunization create.
=> Documentation for R4 Immunization Write

content/millennium/r4/medications/immunization.md, lib/resources/example_json/r4_examples_immunization.rb, lib/resources/r4/immunization.yaml
Adding Documentation for Immunization update.
=> Documentation for R4 Immunization Update

Gemfile, content/millennium/r4/financial/coverage.md, lib/resources/example_json/r4_examples_coverage.rb
Pull request for adding encounter as a search criteria for coverage.
=> Updated content for coverage search by encounter

content/millennium/r4/medications.md
=> Add MedicationRequest link to Medication page

content/millennium/dstu2/diagnostic/observation.md, content/millennium/r4/diagnostic/observation.md
=> Observation formatted comment documentation update

content/millennium/dstu2/general-clinical/allergy-intolerance.md, content/millennium/dstu2/general-clinical/condition.md, content/millennium/dstu2/general-clinical/procedure.md, lib/resources/example_json/dstu2_examples_condition.rb
I went through the General Clinical section and fixed some inconsistencies associated with their JSON. (My IDE also removed some trailing white space.)
**AllergyIntolerance**:
I changed the UPDATE example to use the closed endpoint and updated the URL to match the ID in the JSON.
Closed endpoint:
Matching Ids:
**Condition**:
I updated the Health-Concern examples to use one that currently exists. This was done so the retrieve by id example will not return a 404. The Create and Update examples have been given a full, closed URL, and the Update example has been modified to an example that should succeed.
Updated read with a new Health-Concern:
Condition Update change:
**AllergyIntolerance, Condition, & Procedure**:
I added the disclaimer message after each JSON example in these 3 resources.
=> Update General Clinical JSON inconsistencies

content/millennium/r4/scheduling/appointment.md
Adding notes about video visit functionality, since the documentation does not reflect that it is for specific installations.
=> Adding notes about video visits

content/millennium/dstu2/entities/contract.md, content/millennium/dstu2/entities/person.md, lib/resources/example_json/dstu2_examples_person.rb
I went through the Entities resources in DSTU2 and updated some JSON inconsistencies.
Person:
I updated the combined person entry to one that currently exists.
In Person and Contract:
I went through and added the disclaimer after each response. A working example of this can also be seen in the previous picture.
=> Update Entities JSON inconsistencies

content/millennium/dstu2/care-provision/care-plan.md, content/millennium/dstu2/care-provision/goal.md, content/millennium/dstu2/care-provision/procedure-request.md, lib/resources/example_json/dstu2_examples_procedure_request.rb
Update to the ProcedureRequest example where so the example works in Sandbox. Also, added disclaimers of data changing after responses.
CarePlan Update:
Goal Update:
ProcedureRequest Update:
=> DSTU2 CareProvision Inconsistency Updates

lib/resources/example_json/r4_examples_encounter.rb, lib/resources/r4/encounter.yaml
=> Modifying identifier type and system examples to values that are supported

content/millennium/dstu2/infrastructure/binary.md, content/millennium/dstu2/infrastructure/document-reference.md, lib/resources/dstu2/document_reference.yaml, lib/resources/example_json/dstu2_examples_document_reference.rb
Went through Infrastructure for DSTU2 to look for inconsistencies.
Binary:
- Added disclaimers
Document Reference:
- Added disclaimers
- Moved create around for consistency placement with other resources
- Changed to snipped for brevity in some examples
=> DSTU2 Infrastructure Inconsistencies update

content/millennium/r4/diagnostic/observation.md, lib/resources/example_json/r4_examples_observation.rb
Added type field to Observation reference range.
Local Validation:
=> Update observation reference range

content/millennium/r4/general-clinical/condition.md, lib/resources/r4/condition.yaml
=> Add documentation for R4 Condition diagnosis write

content/millennium/r4/general-clinical/condition.md, lib/resources/r4/condition.yaml
=> Add documentation for R4 Condition diagnosis update

content/millennium/r4/general-clinical/procedure.md, lib/resources/example_json/r4_examples_procedure.rb, lib/resources/r4/procedure.yaml
The R4 documentation for Procedure Create.
Local Validation:
Validation:
Make sure the Procedure page loads and all of the links work properly.
=> Add Documentation for R4 Procedure Create

content/millennium/dstu2/scheduling/appointment.md, content/millennium/dstu2/scheduling/schedule.md, content/millennium/dstu2/scheduling/slot.md, lib/resources/example_json/dstu2_examples_schedule.rb, lib/resources/example_json/dstu2_examples_slot.rb
Update to the Scheduling resources (Appointment, Slot, and Schedule) examples so the examples work in Sandbox. Also, added disclaimers of data changing after responses, including for appointment a disclaimer that the create/update examples will not work because of slots filling up and appointments occurring.
**Appointment Update:**
Disclaimers:
**Schedule Update:**
New id & response:
Disclaimer:
**Slot Update:**
New id:
Disclaimer:
=> DSTU2 Scheduling Inconsistency Updates

content/millennium/r4/financial/coverage.md, lib/definition_table_generator.rb, lib/resources/example_json/r4_examples_coverage.rb, lib/resources/r4/coverage.yaml
Changes:
* Added encounter request body.
* Added encounter-extension body field.
Local Verification:
=> Added documentation for Coverage-By-Encounter Write 

content/millennium/r4/encounters/encounter.md, lib/resources/r4/encounter.yaml
Description
----
Adds the Accept header for the Create example and switches the participant.period and participant.individual examples.
PR Checklist
----
=> Fix Encounter R4 examples

lib/resources/example_json/r4_examples_appointment.rb
Description
----
Remove top-level array from R4 Appointment create example
PR Checklist
----
=> Update R4 Appointment create example body. Fixes #383

content/millennium/r4/financial/coverage.md
Description
----
Added documentation for R4 Coverage (Encounter level) Delete.
PR Checklist
----
=> Added documentation for R4 Coverage (Encounter level) Delete

content/millennium/r4/diagnostic/observation.md, lib/resources/example_json/r4_examples_observation.rb
Description
----
Added basedOn under the fields being returned and also in the example
PR Checklist
----
=> Added documentation for Observation BasedOn

content/millennium/r4/scheduling/appointment.md, lib/resources/example_json/r4_examples_appointment.rb, lib/resources/r4/appointment.yaml
Description
----
Adding documentation for creating new Appointments with a status of 'proposed'.
Local Verification - Before
----
Local Verification - After
---
PR Checklist
----
=> Proposed Appointment Write Documentation Updates

content/millennium/r4/diagnostic/observation.md
Description
----
Update documentation to specify proprietary code searches are not supported
PR Checklist
----
=> Observation R4 proprietary code search not supported

content/millennium/r4/scheduling/appointment.md, lib/resources/example_json/r4_examples_appointment.rb, lib/resources/r4/appointment_patch.yaml
Description
OPENSVC-10115 Appointment request patch to booked.
PR Checklist
----
Before : 
After:
=> Appointment request patch

content/authorization/openid-connect.md
Description
----
Update stale commentary re: OpenID Connect support
PR Checklist
----
=> Update stale commentary re: OpenID Connect support

content/millennium/r4/scheduling/appointment.md, lib/resources/example_json/r4_examples_appointment.rb, lib/resources/r4/appointment.yaml
Description
----
Adding reasonCode for R4 Appointment Creates.
Screenshots:
PR Checklist
----
=> R4 Appointment Write reasonCode enhancement

content/millennium/r4/care-provision.md, content/millennium/r4/care-provision/service-request.md, content/millennium/r4/proprietary-codes-and-systems.md, layouts/millennium_r4_sidebar.html, lib/resources/example_json/r4_examples_service_request.rb, lib/resources/r4/service_request.yaml
Description
----
PR Checklist
----
=> Add ServiceRequest read and search documentation

content/millennium/r4/scheduling/appointment.md, lib/resources/example_json/r4_examples_appointment.rb, lib/resources/r4/appointment_patch.yaml
Description
----
Updated documentation for Appointment reasonCode Patch
PR Checklist
----
=> R4 Appointment reasonCode Patch Enhancement

lib/resources/r4/appointment_patch.yaml
Description
----
Updated documentation for Appointment reasonCode Patch
PR Checklist
----
=> R4 Appointment reasonCode Patch Update

content/millennium/r4/conformance/structure-definition.md, content/millennium/r4/encounters/encounter.md, lib/resources/example_json/r4_examples_encounter.rb, lib/resources/r4/encounter.yaml
Description
----
Adding new Sweden required fields to the Encounter read/search documentation.
Menu Additions:
Extension Added to Body:
New Terminology Bindings:
New Extension Fields:
PR Checklist
----
=> Added Sweden required Fields for Encounter read and search.

lib/resources/r4/financial_transaction.yaml
Description
----
Strings should be decimals
PR Checklist
----
=> Fix type of FinancialTransaction valueMoney.value examples. Fixes #393

content/millennium/r4/care-provision.md, content/millennium/r4/care-provision/care-plan.md, layouts/millennium_r4_sidebar.html, lib/resources/dstu2/care_plan.yaml, lib/resources/example_json/r4_examples_care_plan.rb, lib/resources/r4/care_plan.yaml
Description
The R4 documentation for CarePlan Read and Search
pre-merge validation:
PR Checklist
----
=> R4 CarePlan Read and Search Documentation Added 

content/smart.md
Description
----
Need to update the link to the fhir-client-cerner-additions library with branch renames.
PR Checklist
----
=> Update link for fhir-client-cerner-additions code

content/millennium/overview.md, layouts/head.html, layouts/millennium_diff_table.html, static/css/documentation.css, static/js/documentation.js, static/js/millennium_diff_table.js
Description
----
Added a table to the overview page that shows the DSTU2 and R4 resources and their supported actions for comparison.
PR Checklist
----
=> Add diff table to millennium overview page

layouts/millennium_dstu2_sidebar.html, layouts/millennium_overview_sidebar.html, layouts/millennium_r4_sidebar.html, layouts/soarian_dstu2_sidebar.html, static/css/documentation.css, static/js/documentation.js
Description
----
Added "Expand All"/"Collapse All" buttons to all sidebars that have expandable buttons.
PR Checklist
----
=> Add "Expand All"/"Collapse All" button to sidebar

content/millennium/dstu2/scheduling/slot.md
Description
----
PR Checklist
----
=> Fix DSTU2 Slot search parameter example for 'start'

lib/resources/example_json/r4_examples_observation.rb
Description
----
Changed the performer field in the example, to have multiple performers.
PR Checklist
----
=> R4 Observation Multiple Performers

content/millennium/r4/scheduling/appointment.md, lib/resources/example_json/r4_examples_appointment.rb
Description
----
This updates the video visit example for the new public sandbox.
PR Checklist
----
=> Update Appointment Video Visit Example

content/millennium/r4/diagnostic/observation.md, lib/resources/example_json/r4_examples_observation.rb
Description
----
Added reads documentation
Before: 
After(on Local Machine):
PR Checklist
----
=> R4 Observation Charted Read

content/millennium/r4/diagnostic/observation.md, lib/resources/example_json/r4_examples_observation.rb
Description
----
Updated the id in read link
Updated example 
Local Validation:
PR Checklist
----
=> R4 Observation Charted Read fix and example update

content/millennium/r4/scheduling/appointment.md
[Description](url)
----
Appointment PATCH requires both read and write scopes. This instruction is being added to the implementation notes under PATCH. 
Screenshot before merging the changes : 
Final changes : 
PR Checklist
----
=> Appointment PATCH Implementation notes

content/millennium/r4/entities/organization.md
Description
----
Updated the Organization.md and changed the patient from false to true in authorization_types.
PR Checklist
----
=> Updated patient to true in authorization_types for Organization

content/millennium/dstu2/infrastructure/binary.md, content/millennium/dstu2/infrastructure/document-reference.md, content/millennium/faq/common-issues.md, content/millennium/r4/entities/organization.md, content/millennium/r4/general-clinical/allergy-intolerance.md, content/millennium/r4/general-clinical/condition.md, content/millennium/r4/general-clinical/procedure.md, content/millennium/r4/individuals/patient.md, content/soarian/dstu2/individuals/patient.md, lib/resources/example_json/dstu2_examples_binary.rb
Description
----
This PR replaces a non-space whitespace character that shows up in various files with a space. As there are no content changes, no verification screenshots are necessary. Fixes #426 
PR Checklist
----
=> Remove non-space whitespace characters. Fixes #426

content/millennium/r4/diagnostic/observation.md, lib/definition_table_generator.rb, lib/field_definition_table.erb, lib/resources/example_json/r4_examples_observation.rb, lib/resources/r4/observation.yaml, lib/resources/r4/types.yaml
Description
----
Added Observation Creates for Laboratory and Vital Signs in millennium R4 entities. 
PR Checklist
----
=> R4 Observation Labs and Vitals Writes

content/millennium/r4/individuals/person.md
Description
----
Added patient to authorization_types of R4 Person search and retrieve by id.
Validation
----
PR Checklist
----
=> Add Patient to Auth_Types of R4 Person Search and Retrieve by Id

content/millennium/r4/individuals/patient.md
Description
----
Add Patient to the Authorization Types section for Search and Retrieve by Id R4 Patient resource. 
Validation
----
PR Checklist
----
=> Add Patient to Auth Types of R4 Patient search and retrieve by Id

content/millennium/r4/proprietary-codes-and-systems.md, lib/resources/example_json/r4_examples_medication_request.rb, lib/resources/r4/medication_request.yaml, lib/resources/r4/medication_request_contained_medication.yaml
Description
----
MedicationRequest - Expose Order Synonym Id in the MedicationRequest.medicationCodeableConcept
Screenshots before:
Screenshots After changes:
PR Checklist
----
=> Med req r4 synonym

content/millennium/r4/encounters/encounter.md, lib/resources/example_json/r4_examples_encounter.rb
Description
----
All changes have been made and exposed appointment to read and search response
Screenshots for read and search have been added.
PR Checklist
----
=> R4 encounter expose appointment

lib/resources/example_json/r4_examples_observation.rb, lib/resources/r4/observation.yaml
Description
----
Replaced Observation proprietary code with standard code
PR Checklist
----
=> Update observation vital sign proprietory code with standard code

lib/resources/example_json/r4_examples_encounter.rb, lib/resources/r4/encounter_patch.yaml
Description
----
PR Checklist
----
Previously:
Change:
Updated Change:
=> Added Encounter patch for payment-collection-status extension

content/millennium/r4/medications/medication-request.md, lib/resources/example_json/r4_examples_medication_request.rb, lib/resources/r4/medication_request_patch.yaml
Description
----
Added MedicationRequest PATCH documentation.
PR Checklist
----
=> Added MedicationRequest PATCH documentation

content/millennium/r4/encounters/encounter.md, lib/resources/example_json/r4_examples_encounter.rb
This reverts commit 016264dcb142d3a3ebc439dcef5ea33647d783b0.
Description
----
PR Checklist
----
=> Revert "R4 encounter expose appointment (#467)"

lib/resources/example_json/r4_examples_encounter.rb, lib/resources/r4/encounter_patch.yaml
Description
----
PR Checklist
----
=> [Encounter] Patch for estimated-financial-responsibility-amount Extension

content/millennium/r4/conformance/structure-definition.md, content/millennium/r4/medications/medication-request.md, lib/resources/example_json/r4_examples_medication_request.rb
Description
----
Updated medicationRequest.dosageInstrction with CDL display using a custom extension. 
Screenshots before changes merged : 
PR Checklist
----
=> R4 MedicationRequest CDL

content/millennium/r4/care-provision/care-team.md, content/millennium/r4/diagnostic/observation.md
Description
----
Updated sandbox URL's to Prod URL's for Observation and CareTeam Resources
PR Checklist
----
=> Update wrong URL's for Observation and CareTeam

content/millennium/r4/care-provision/care-team.md
Description
----
Minor fix: Added Scope changes updated for CareTeam resource
PR Checklist
----
=> R4 CareTeam resource Scopes updated

content/millennium/r4/diagnostic/observation.md
Description
----
Added Vital Signs wiki reference page. 
PR Checklist
----
=> R4 observation vitals

lib/resources/example_json/r4_examples_relatedperson.rb
Description
----
R4 RelatedPerson Expose ids of array fields on read/search
PR Checklist
----
=> R4 RelatedPerson Read/Search Expose Ids

content/millennium/r4/individuals/related-person.md, lib/resources/example_json/r4_examples_relatedperson.rb, lib/resources/r4/related_person.yaml
Description
----
Created documentation for the relationship-level extension
Added extension to read/search examples (and narrative)
PR Checklist
----
=> R4 RelatedPerson Expose Extension relationship-level Read/Search

content/millennium/dstu2/medications/medication-administration.md, lib/resources/example_json/dstu2_examples_medication_administration.rb
Description
----
Added implementation notes about how to calculate actual medication quantity administered in DSTU2 Medication Administration.
PR Checklist
----
=> Added Implementation Notes about quantity to DSTU2 Medication Administration

content/millennium/r4/conformance/structure-definition.md
Description
----
Add relationship-level and related-person-encounter structure defs
I also added all the missing structure definitions
PR Checklist
----
=> Missing structure definitions

lib/resources/r4/observation.yaml
Description
----
Updated Performer.extension bindings and examples.
PR Checklist
----
=> R4 Observation Labs

content/millennium/r4/encounters/encounter.md, lib/resources/example_json/r4_examples_encounter.rb
Description
----
This PR
PR Checklist
----
=> R4-Encounter-expose-appointment

lib/resources/r4/service_request.yaml
Description
----
Updating Service Request coding system to include LOINC codes.
PR Checklist
----
=> Service Request code update for loinc details.

content/millennium/r4/diagnostic/observation.md, lib/resources/example_json/r4_examples_observation.rb, lib/resources/r4/observation.yaml
Description
----
Added Observation Labs Update for R4.
PR Checklist
----
=> R4 Observation Labs Update

content/millennium/r4/medications/medication-request.md
Description
----
Documented Identifier field for Medication Request 
Screenshot of the changes made:
----
PR Checklist
----
=> R4 Medication request reflect support for identifier

content/millennium/dstu2/medications/medication-administration.md
Description
----
Updated documentation for Medication Administration search parameter 'effectivetime' along with additional examples.
PR Checklist
----
=> DSTU2 MedAdministration Search documentation update for effectivetime field

content/authorization.md
Description
----
PR Checklist
----
=> Update confidential client doc

content/millennium/r4/security.md, content/millennium/r4/security/provenance.md, layouts/millennium_r4_sidebar.html, layouts/security.html, lib/resources/example_json/r4_examples_provenance.rb, lib/resources/r4/provenance.yaml
The R4 documentation for Provenance Read, Search, and Create.
Validation:
Make sure the Security and Provenance pages load and all of the links work properly.
Screenshots after few changes
=> R4 Provenance Read, Search, and Create

content/millennium/r4/scheduling.md, content/millennium/r4/scheduling/slot.md, layouts/millennium_r4_sidebar.html, lib/resources/example_json/r4_examples_slot.rb, lib/resources/r4/slot.yaml
Description
----
The R4 documentation for Slot Read and Search
Pre merge validation screenshots
PR Checklist
----
=> R4 Slot Read and Search documentation

content/millennium/r4/care-provision.md, content/millennium/r4/care-provision/goal.md, layouts/millennium_r4_sidebar.html, lib/resources/example_json/r4_examples_goal.rb, lib/resources/r4/goal.yaml
Description
----
PR Checklist
----
=> R4 Goal Read and Search Documentation

content/millennium/r4/medications/immunization.md, lib/resources/example_json/r4_examples_immunization.rb
Description
----
Adding R4 Immunization Documentation for Patient Access.
-----
PR Checklist
----
=> R4 Immunization Documentation added for Patient Access

content/millennium/r4/care-provision/care-plan.md, lib/resources/example_json/r4_examples_care_plan.rb
Description
----
Adding R4 Care Plan Documentation for Patient Access.
PR Checklist
----
=> R4 Care plan Documentation added for Patient Access

content/millennium/r4/care-provision/care-team.md, lib/resources/example_json/r4_examples_care_team.rb
Description
----
Adding R4 Care Team Documentation for Patient Access.
----
PR Checklist
----
=> R4 Care team Documentation added for Patient Access

content/millennium/r4/entities.md, content/millennium/r4/entities/consent.md, layouts/millennium_r4_sidebar.html, lib/resources/example_json/r4_examples_consent.rb, lib/resources/r4/consent.yaml
Description
----
Added r4 consent to fhir.cerner.com
-----
PR Checklist
----
=> Added r4 consent to fhir.cerner.com

content/millennium/r4/encounters/encounter.md, lib/resources/example_json/r4_examples_encounter.rb
Description
----
R4 Encounter updated for patient access
----
PR Checklist
----
=> R4 Encounter updated for patient access

content/millennium/r4/general-clinical/condition.md, lib/resources/example_json/r4_examples_capabilitystatement.rb, lib/resources/example_json/r4_examples_condition.rb, lib/resources/r4/condition.yaml
Description
----
Health Concern support added for Condition category
Patient Access support for Condition
PR Checklist
----
=> R4_HealthConcern_Support

content/millennium/r4/documents/document-reference.md, lib/resources/example_json/r4_examples_document_reference.rb
Description
----
Updated fhir.cerner.com to add  Patient Access support for DocumentReference read and search capability..
PR Checklist
----
=> R4 DocumentReference Patient Access documentation for read and search

content/millennium/r4/devices/device.md, lib/resources/example_json/r4_examples_device.rb
Description
----
Introducing Device Patient Access
PR Checklist
----
=> Device Patient Access Updated

content/millennium/r4/entities/consent.md
Description
----
Consent patient access documentation
screenshot before merge
----
PR Checklist
----
=> Consent patient access documentation

content/millennium/r4/entities/organization.md
Description
----
Adding new search parameters for R4 Organization (`type`, and `_count`)
Validation before merge
----
**Organization**
PR Checklist
----
=> R4 Organization 'type' and '_count' search parameters.

content/millennium/r4/individuals/related-person.md, lib/resources/example_json/r4_examples_relatedperson.rb, lib/resources/r4/related_person.yaml, lib/resources/r4/related_person_patch.yaml
Description
----
Added Create and Patch for Encounter Level Related Person
PR Checklist
----
- [ x ] Screenshot(s) of changes attached before changes merged.
=> R4 RelatedPerson Create and Patch

content/millennium/r4/individuals/related-person.md, lib/resources/example_json/r4_examples_relatedperson.rb
Description
----
Updates to http://fhir.cerner.com/millennium/r4/individuals/related-person/ for related person encounter level r4 read/search functionality
Changes before merged
----
PR Checklist
----
=> Related Person Encounter R4 Read/Search Updates

content/millennium/r4/entities.md, content/millennium/r4/entities/location.md, content/millennium/r4/proprietary-codes-and-systems.md, layouts/millennium/r4/sidebar.html, lib/resources/example_json/r4_examples_location.rb, lib/resources/r4/location.yaml
Description
----
Updated the Location resource page to reflect support for custom attributes.
PR Checklist
----
Screenshots Before Changes Merged
----
=> Update Location to reflect custom attribute support

lib/resources/example_json/dstu2_examples_contract.rb
Description
----
Adding search mode inside response body for contract resource.
----
PR Checklist
----
=> Adding search mode inside response body for contract resource

content/millennium/r4/documents/document-reference.md
DocRefCcd support fix added for Documentreference
Description
----
PR Checklist
----
=> R4_docref_ccd_support_fix

lib/resources/example_json/r4_examples_relatedperson.rb, lib/resources/r4/related_person_patch.yaml
Description
----
Add documentation for RelatedPerson add address operation
PR Checklist
----
=> RelatedPerson Add Address Operation

content/millennium/r4/entities/consent.md
Description
----
Added documentation for R4 consent search
PR Checklist
----
=> R4 Consent Search Documentation

lib/resources/example_json/r4_examples_relatedperson.rb, lib/resources/r4/related_person_patch.yaml
Description
----
PR Checklist
----
=> RelatedPerson Patch Family Name

content/millennium/r4/entities/location.md, lib/resources/example_json/r4_examples_location.rb
Description
----
Fix a couple Location example URLs
PR Checklist
----
=> Update R4 Location example URLs

content/millennium/r4/medications/medication-request.md, lib/resources/example_json/r4_examples_medication_request.rb
Added Hardcoded Extension to MedicationRequest
Description
----
PR Checklist
----
=> [R4] MedicationRequest Add Sweden HardCoded extensions

content/millennium/r4/scheduling/slot.md, lib/resources/example_json/r4_examples_slot.rb
Description
----
PR Checklist
----
=> Support patient access for r4 Slot read and search capability

content/millennium/r4/care-provision/service-request.md
Description
----
Add `basedOn` to the list of fields on ServiceRequest
PR Checklist
----
=> Add ServiceRequest basedOn to the list of fields

content/millennium/r4/scheduling/schedule.md, lib/resources/example_json/r4_examples_schedule.rb
Description
----
Updated docs for R4-schedule patient access
PR Checklist
----
=> updated docs for R4-schedule patient access

lib/resources/r4/related_person_patch.yaml
Description
----
Adding test and remove operation for related person identifier.
PR Checklist
----
=> adding test and remove operation for identifier

content/millennium/r4/individuals/related-person.md, lib/resources/example_json/r4_examples_relatedperson.rb
Description
----
Updated docs for related person patient access
PR Checklist
----
=> Updated docs for related person patient access

content/smart.md
Description
----
PR Checklist
----
=> Clarify definition of SMART without FHIR

lib/resources/example_json/r4_examples_patient.rb, lib/resources/example_json/r4_examples_person.rb
Description
----
Updated docs for patient and person for telecom (added extension)
PR Checklist
----
=> Updated docs for patient and person for telecom (added extension)

content/authorization.md
Description
----
PR Checklist
----
=> Clarify the duration of unused offline_access scopes

content/millennium/r4/other/binary.md
Description
----
Binary Patient Access Updated
PR Checklist
----
=> Binary Patient Access Updated

content/millennium/r4/entities/organization.md
Description
----
Name parameter introduced in Organization Search
PR Checklist
----
=> Name parameter introduced in Organization Search

lib/resources/example_json/r4_examples_relatedperson.rb, lib/resources/r4/related_person_patch.yaml
Description
----
Changes for Related Person address test and remove operation.
PR Checklist
----
=> Related person address test and remove operation changes.

lib/resources/example_json/r4_examples_relatedperson.rb, lib/resources/r4/related_person_patch.yaml
Description
----
Adding given parameter to RelatedPerson Patch
PR Checklist
----
=> Updated related person current name given patch

lib/resources/example_json/r4_examples_relatedperson.rb, lib/resources/r4/related_person_patch.yaml
Description
----
PR Checklist
----
=> Updated related person current name suffix patch

lib/resources/example_json/r4_examples_relatedperson.rb, lib/resources/r4/related_person_patch.yaml
Description
----
Added Added the add operation for telecom
PR Checklist
----
=> Added the add operation for telecom

content/millennium/r4/conformance.md, content/millennium/r4/conformance/operation-definition.md, content/millennium/r4/entities/organization.md, layouts/millennium/r4/sidebar.html, lib/resources/example_json/r4_examples_operation_definition.rb, lib/resources/example_json/r4_examples_organization.rb
Description
----
Added documentation for the Organization $get-cg-for-mrcu special operation.
PR Checklist
----
Screenshots before changes merged
----
=> Add docs for Organization Caregiver search operation

content/millennium/r4/care-provision/service-request.md, lib/resources/example_json/r4_examples_service_request.rb, lib/resources/example_json/r4_examples_slot.rb
Description
----
Added doc for ServiceRequest read and search capability
PR Checklist
----
=> Support patient access for r4 ServiceRequest read and search capability

content/bad_route.md
Description
----
Fixes #574 
PR Checklist
----
=> Update the link on the bad route page

content/millennium/r4/general-clinical/condition.md, lib/resources/example_json/r4_examples_condition.rb
Description
----
OPENSVC-16532: [Conditions] updated the fhir docs for Health Concerns.
PR Checklist
----
=> OPENSVC-16532: R4 Condition updated FHIR doc for Health concerns

content/millennium/r4/general-clinical/condition.md, lib/resources/example_json/r4_examples_condition.rb
Reverts cerner/fhir.cerner.com#571
=> Revert "OPENSVC-16532: R4 Condition updated FHIR doc for Health concerns"

content/millennium/r4/proprietary-codes-and-systems.md, content/millennium/r4/scheduling/appointment.md, lib/resources/example_json/r4_examples_appointment.rb, lib/resources/r4/appointment.yaml
Description
----
Added the documentation for appointment.serviceCategory
PR Checklist
----
=> Added documentation for Appointment ServiceCategory

content/millennium/r4/scheduling/appointment.md, lib/resources/example_json/r4_examples_appointment.rb
Description
----
Documentation for Slot reference in appointment read/search.
PR Checklist
----
=> Added Slot Id in Appointment read

content/millennium/r4/scheduling/slot.md, lib/resources/r4/slot.yaml
Description
----
Fixes #588 
PR Checklist
----
=> Update R4 Slot proprietary codes terminology binding link

content/millennium/r4/proprietary-codes-and-systems.md, content/millennium/r4/scheduling/appointment.md, lib/resources/example_json/r4_examples_appointment.rb, lib/resources/r4/appointment.yaml
Description
----
Return Cancellation Reason in Appointment Read/Search
PR Checklist
----
=> Appointment read/search cancelled reason changes

content/millennium/r4/scheduling/appointment.md, lib/resources/example_json/r4_examples_appointment.rb
Description
----
Return Patient Instruction in Appointment Read/Search
PR Checklist
----
=> Appointment read/search patient instruction changes

content/millennium/r4/individuals/related-person.md
Description
----
Updated the Notes Related to Related Person search parameter '-relationship-level'
PR Checklist
----
=> Updated the notes of -relationship-level search parameter

lib/resources/example_json/r4_examples_appointment.rb, lib/resources/r4/appointment.yaml
Description
----
Update Appointment serviceType Create Example to mapped code in C1941
PR Checklist
----
=> Update Appointment serviceType Create Example

lib/resources/r4/schedule.yaml, lib/resources/r4/slot.yaml
Description
----
Update serviceType terminology bindings for Schedule and Slot
PR Checklist
----
=> Update serviceType terminology bindings

lib/resources/example_json/r4_examples_condition.rb, lib/resources/r4/condition.yaml
Health Concern category system and code changes
Description
----
PR Checklist
----
=> R4-Condition-HC-Changes

content/millennium/r4/entities/organization.md
Description
----
Added Note to Organization search information, to provide details on search option with out system.
PR Checklist
----
=> OPENSVC-15187: Update Organization identifier search to support with or without system

content/millennium/r4/proprietary-codes-and-systems.md, content/millennium/r4/scheduling/appointment.md, lib/resources/example_json/r4_examples_appointment.rb, lib/resources/r4/appointment_patch.yaml
Description
----
Appointment documentation update for appointment.cancelationReason add operation when performing an Appointment PATCH operation
PR Checklist
----
=> Appointment PATCH appointment.CancelationReason

content/millennium/r4/scheduling/appointment.md
Description
----
Clarify verbiage around video visits and supported vendors.
Fixes https://github.com/cerner/fhir.cerner.com/issues/600
PR Checklist
----
=> Clarify Video Visit functionality and supported vendors

content/millennium/r4/definitional-artifacts.md, content/millennium/r4/definitional-artifacts/questionnaire.md, layouts/millennium/r4/definitional-artifacts.html, layouts/millennium/r4/sidebar.html, lib/resources/example_json/r4_examples_questionnaire.rb, lib/resources/r4/questionnaire.yaml
Description
----
Documentation for Questionnaire read and search
PR Checklist
----
=> Questionnaire Read and Search

content/millennium/r4/medications/medication-request.md, lib/resources/r4/medication_request.yaml
Description
----
PR Checklist
----
=> MedicationRequest - search - intent parameter

lib/resources.rb, spec/lib/resources_spec.rb, static/css/documentation.css
Description
----
Creating a helper to add beta tags to resources and resource actions.
PR Checklist
----
=> Adding a beta tag helper

content/millennium/r4/definitional-artifacts/questionnaire.md
Description
----
Adding Questionnaire Beta Tag
PR Checklist
----
=> Questionnaire Beta Tag

content/millennium/r4/conformance/structure-definition.md, content/millennium/r4/financial.md, content/millennium/r4/financial/charge-item.md, content/millennium/r4/proprietary-codes-and-systems.md, layouts/millennium/r4/sidebar.html, lib/resources/example_json/r4_examples_charge_item.rb, lib/resources/r4/charge_item.yaml
Description
----
Adding documentation for retrieve by Id for ChargeItem read
PR Checklist
----
=> ChargeItem read documentation

content/millennium/r4/care-provision/care-team.md
Description
removed encounter scope for careteams
PR Checklist
----
=> CareTeam[r4]:remove encounter scope

lib/resources/example_json/r4_examples_patient.rb, lib/resources/example_json/r4_examples_person.rb
Description
----
Patient/Person iso21090-TEL-address Extension valueUrl Example
valueUrl should not contain spaces 
PR Checklist
----
=> Patient/Person iso21090-TEL-address Extension valueUrl Example

content/millennium/r4/conformance/structure-definition.md, content/millennium/r4/medications/medication-request.md, lib/resources/example_json/r4_examples_medication_request.rb
Description
----
PR Checklist
----
=> OPENSVC-18758: Pharmacy Verification Status custom extension

content/millennium/r4/conformance/structure-definition.md, content/millennium/r4/medications/medication-request.md, lib/resources/example_json/r4_examples_medication_request.rb
Reverts cerner/fhir.cerner.com#609
=> Revert "OPENSVC-18758: Pharmacy Verification Status custom extension"

lib/resources/r4/observation.yaml
Description
----
PR Checklist
----
=> OPENSVC-19588: R4 Observation Duplicate terminology bindings display on fhir.cerner.com

content/millennium/r4/conformance/structure-definition.md
Description
----
Note and Note-Allowed Structure Definitions
PR Checklist
----
=> Note and Note-Allowed Structure Definitions

content/millennium/r4/general-clinical/allergy-intolerance.md, lib/resources/example_json/r4_examples_allergy_intolerance.rb
…rance
Description
Added search parameter "_revinclude" and example of response body.
PR Checklist
----
=> R4 Allergy Intolerance: Added revinclude as search parameters

content/millennium/r4/conformance/structure-definition.md, content/millennium/r4/financial/charge-item.md, content/millennium/r4/proprietary-codes-and-systems.md, lib/resources/example_json/r4_examples_charge_item.rb, lib/resources/r4/charge_item.yaml
Description
----
Adding bill code schedule extension for ChargeItem and updating proprietary codes documentation for Account
PR Checklist
----
=> Charge item changes for bill code schedule extension

content/millennium/r4/conformance/capability-statement.md
Description
----
CapabilityStatement Beta Interaction Documentation
PR Checklist
----
=> CapabilityStatement Beta Interaction Documentation

lib/resources/example_json/r4_examples_questionnaire.rb
Description
----
Questionnaire Example with Type Quantity
PR Checklist
----
=> Questionnaire Example with Type Quantity

content/millennium/r4/diagnostic.md, content/millennium/r4/diagnostic/questionnaire-response.md, layouts/millennium/r4/sidebar.html, lib/resources/example_json/r4_examples_questionnaire_response.rb, lib/resources/r4/questionnaire_response.yaml
Description
----
QuestionnaireResponse Beta Overview
PR Checklist
----
=> QuestionnaireResponse Beta Overview

lib/resources/example_json/r4_examples_questionnaire.rb
Description
----
Update item.item linkIds to have the categoryRefId-taskAssayCd format
PR Checklist
----
=> item.item.linkId_update: Update fhir.cerner.com example

lib/resources/r4/document_reference.yaml
Description
----
Updated final to current in status section of R4 Document Reference update
Jira Link: https://jira2.cerner.com/browse/OPENSVC-19968
PR Checklist
----
----
=> Updated final to current in status section of R4 Document Reference update

content/millennium/r4/conformance/structure-definition.md, content/millennium/r4/financial/charge-item.md, lib/resources/example_json/r4_examples_charge_item.rb
Description
----
Update to ChargeItem.Reason to expose the Priority field.
Update Priority to be a standalone extension.
PR Checklist
----
Screenshots
----
=> [ChargeItem] Expose Priority on ChargeItem.Reason

content/millennium/r4/conformance/structure-definition.md, content/millennium/r4/individuals/related-person.md, content/millennium/r4/proprietary-codes-and-systems.md, lib/resources/example_json/r4_examples_relatedperson.rb, lib/resources/r4/related_person.yaml
Description
----
Update changes for RelatedPerson relationship relation read and write enhancement
!![image](https://user-images.githubusercontent.com/57788817/118868665-11860100-b902-11eb-933a-441ae58f1627.png)
PR Checklist
----
=> R4 RelatedPerson relationship relation read/search and write enhancement

content/millennium/r4/conformance/structure-definition.md
Description
----
StructureDefinition choice-answer
PR Checklist
----
=> StructureDefinition choice-answer

content/millennium/r4/entities/organization.md
Description
----
Before
PR Checklist
----
=> R4 Organization Search Type only standard identifiers

content/millennium/r4/individuals/practitioner.md, lib/resources/example_json/r4_examples_practitioner.rb, lib/resources/r4/practitioner.yaml
Description
----
Added Practitioner.qualification field and examples to R4 Practitioner resource
Jira:
----
https://jira2.cerner.com/browse/OPENSVC-20284
Screenshots before merge
----
PR Checklist
----
=> Added Practitioner.qualification field and examples to R4 Practitioner resource

lib/resources/example_json/r4_examples_relatedperson.rb, lib/resources/r4/related_person.yaml, lib/resources/r4/related_person_patch.yaml
=> Updating the fhir.cerner.com for relationship extensions

lib/resources/r4/encounter.yaml
Description
Update Encounter create documentation with SNOMED code details.
----
PR Checklist
----
=> Update Encounter create documentation with SNOMED code details.

content/millennium/r4/medications/immunization.md, lib/resources/example_json/r4_examples_immunization.rb
Description
----
OPENSVC-18086: Update fhir.cerner.com documentation with details about Immunization revinclude Provenance search.
PR Checklist
----
=> Update fhir.cerner.com documentation with details about Immunization revinclude Provenance search.

lib/resources/r4/immunization.yaml
Description
----
Docs update for Immunization Update action
PR Checklist
----
=> Docs update for Immunisation Update action

lib/resources/r4/medication_request.yaml
Description
----
PR Checklist
----
=> Remove requirement for dosageInstruction start time when end time is provided

content/millennium/r4/encounters/encounter.md, lib/resources/example_json/r4_examples_encounter.rb
Description
----
PR Checklist
----
=> R4 Encounter: Added revinclude as search parameters

content/millennium/r4/scheduling/slot.md
Description
----
Remove beta tag since known issue is now resolved in the local service
Screenshot Before Merge
----
PR Checklist
----
=> Slot patch remove beta tag

lib/resources/r4/immunization.yaml
Description
----
PR Checklist
----
=> update encounter field to be required for create 

content/millennium/r4/individuals/practitioner.md, lib/resources/example_json/r4_examples_practitioner.rb
Description
----
Updated Practitioner doc for active and count support
PR Checklist
----
=> R4 Practitioner - Updated doc to add active and count search parameter support

content/millennium/r4/general-clinical/procedure.md
Description
----
PR Checklist
----
Before:
After:
=> R4 procedure search by date charted

content/millennium/r4/medications/medication-request.md, lib/resources/example_json/r4_examples_medication_request.rb
Description
----
PR Checklist
----
=> R4 MedicationRequest: Added revinclude as search parameters

lib/resources/example_json/r4_examples_relatedperson.rb, lib/resources/r4/related_person.yaml, lib/resources/r4/related_person_patch.yaml
=> Related Person add operation on relationship, replace operation on relationship extensions and support standard codes for write and patch operations

content/millennium/r4/general-clinical/procedure.md, lib/resources/example_json/r4_examples_procedure.rb
Description
----
Update Procedure documentation with details on Procedure _revinclude Provenance search.
PR Checklist
----
=> Update Procedure documentation with details on Procedure _revinclude Provenance search.

lib/resources/example_json/r4_examples_encounter.rb
Description
----
Update encounter examples with nomenclature reason code.
PR Checklist
----
=> Update encounter examples with nomenclature reason code.

content/millennium/r4/documents/document-reference.md
Description
----
PR Checklist
----
=> [R4] Document Reference Support for Search By Category

content/millennium/r4/diagnostic/observation.md, lib/resources/example_json/r4_examples_observation.rb, lib/resources/r4/observation.yaml
Description
----
PR Checklist
----
=> Vital updates documentation

content/millennium/r4/clinical/care-provision/nutrition-order.md, lib/resources/example_json/r4_examples_nutrition_order.rb
Description
----
Added link for Extension and changed example to show instance-order
PR Checklist
----
=> Updated for NutritionOrder extension and instance-order

content/millennium/r4/base/individuals/patient.md
Description
----
Updated link addresses for patient extensions
PR Checklist
----
=> Patient extension links

content/millennium/r4/base/workflow/appointment.md
Description
----
Add additional clarification for licensing required for video capabilities.
Fixes #671
PR Checklist
----
=> Clarify Video Visit licensing required

content/millennium/r4/base/individuals/related-person.md
Description
----
Changes for RelatedPerson patient level patch Implementation
PR Checklist
----
=> R4 RelatedPerson Patient level patch enhancement

content/millennium/r4/financial/support/coverage.md, lib/resources/example_json/r4_examples_coverage.rb, lib/resources/r4/coverage.yaml
Description
----
Adding Coverage Social Healthcare Write functionality documentation
PR Checklist
----
=> Add R4 Coverage Public Healthcare Write

content/millennium/r4/financial/general/charge-item.md, content/millennium/r4/foundation/conformance/structure-definition.md, lib/resources/r4/charge_item.yaml
Description
----
fhir.cerner.com updates to document the new NDC and QCF custom extensions
PR Checklist
----
=> [ChargeItem][R4] NDC and QCF Extension Updates

content/millennium/r4/financial/general/charge-item.md
Description
----
Added information about account parameter in the chargeItem search.
'reference' refers to search parameter
"Reference" refers to the expected object in response
PR Checklist
----
=> R4 [ChargeItem] : Adding search by account for chargeItem

lib/resources/r4/charge_item.yaml
Description
----
Adding PROCODE to supported listed of codes retrieved.
PR Checklist
----
=> [ChargeItem] [R4] Adding PROCODE code to additional codes

content/millennium/r4/base/individuals/related-person.md, lib/resources/example_json/r4_examples_relatedperson.rb, lib/resources/r4/related_person.yaml
Description
----
Changes for RelatedPerson patient level patch Implementation
PR Checklist
----
=> R4 RelatedPerson Patient level write enhancement 

content/millennium/r4/base/management/encounter.md
Description
----
PR Checklist
----
=> Replaces '.' with ':' in encounter date search examples

content/millennium/r4/foundation/security/provenance.md, lib/resources/r4/provenance.yaml
Description
----
PR Checklist
----
=> Enhance provenance to support R4 Patient resource

lib/resources/example_json/r4_examples_procedure.rb, lib/resources/r4/procedure.yaml
Description
----
Update Procedure documentation with details about procedure performedPeriod field.
PR Checklist
----
=> Update Procedure documentation with details about procedure performedPeriod field.

lib/resources/example_json/r4_examples_coverage.rb
Description
----
Adding coding structure to identify coverage as Charging Category plan type
PR Checklist
----
=> Add Coverage Public Healthcare Coding Structure

content/millennium/r4/base/management/encounter.md, content/millennium/r4/foundation/conformance/structure-definition.md, lib/resources/r4/encounter.yaml
Description
Add military service connected indicator extension to Encounter and Structure Definition and alphabetically sort extensions.
Changes Made
-Table of Contents
<details><summary>Before</summary>
</details>
<details><summary>After</summary><img width="1792" alt="TOC_After" src="https://user-images.githubusercontent.com/87539708/126205038-438f87f2-44d8-4e89-b752-90eecfa67fef.png">
</details>
-Encounter
<details><summary>Before</summary>
</details>
<details><summary>After</summary><img width="1792" alt="Extensions_After" src="https://user-images.githubusercontent.com/87539708/126205141-ee66373a-1bd0-4d75-ab5d-15c5e6d2cc82.png">
</details>
-Structure Definition
<details><summary>Before</summary>
</details>
<details><summary>After</summary><img width="1792" alt="StructureDef_After" …
=> Add military service connected indicator extension to Encounter and Structure Def

content/millennium/r4/base/management/encounter.md
Description
----
PR Checklist
----
=> Encounter: search by identifier

lib/resources/r4/immunization.yaml
Description
----
update encounter field to be required for update
PR Checklist
----
=> update encounter field to be required for update

content/millennium/r4/base/entities/location.md, content/millennium/r4/foundation/conformance/structure-definition.md
Description
----
Documentation for search by Physical Type and also added the note-type custom extension that we missed.
PR Checklist
----
=> Documentation for Location Search by Physical Type

content/millennium/r4/proprietary-codes-and-systems.md, lib/resources/example_json/r4_examples_condition.rb, lib/resources/r4/condition.yaml
Description
----
Return Condition Category Classification Code
PR Checklist
----
=> Condition Category Classification Code

content/millennium/r4/financial/general/account.md, content/millennium/r4/proprietary-codes-and-systems.md, lib/resources/example_json/r4_examples_account.rb, lib/resources/r4/account.yaml
Description
----
PR Checklist
----
=> OPENSVC-20966: Update fhir.cerner.com R4 Account Identifier search system url

content/millennium/r4/base/entities/organization.md
Description
----
Update Organization documentation with details about performing an Organization search all request.
PR Checklist
----
=> Update Organization documentation with details about performing an Organization search all request.

content/millennium/r4/clinical/summary/procedure.md
Description
----
Update Procedure documentation with details about performing a Procedure search by date request.
PR Checklist
----
=> change Procedure search date notes

lib/resources/example_json/r4_examples_allergy_intolerance.rb, lib/resources/example_json/r4_examples_care_plan.rb, lib/resources/example_json/r4_examples_procedure.rb, lib/resources/example_json/r4_examples_schedule.rb
Description
----
https://jira2.cerner.com/browse/OPENSVC-20482
https://jira2.cerner.com/browse/OPENSVC-21357
PR Checklist
----
Schedule Resource:
Procedure Resource:
CarePlan Resource:
Allergy Intolerance:
=> R4 Encoding Narrative Characters to Valid XHTML

content/millennium/r4/financial/general/charge-item.md, content/millennium/r4/foundation/conformance/structure-definition.md, lib/resources/example_json/r4_examples_charge_item.rb, lib/resources/r4/charge_item.yaml
Description
----
ChargeItem procedure and modifier to procedure-code and modifier-code enhancement
PR Checklist
----
=> ChargeItem procedure and modifier to procedure-code and modifier-code enhancement

content/millennium/r4/base/individuals/patient.md, content/millennium/r4/foundation/security/provenance.md, lib/resources/example_json/r4_examples_patient.rb
Description
----
updating fhir for device provenance and patient _revinclude provenance
PR Checklist
----
=> updating fhir for device provenance and patient _revinclude provenance

lib/resources/r4/condition.yaml, lib/resources/r4/document_reference.yaml, lib/resources/r4/encounter.yaml, lib/resources/r4/medication_request.yaml, lib/resources/r4/procedure.yaml
Description
----
Fix for Broken Links for Docref, Condition, Encounter, MedRequest, Procedure
PR Checklist
----
DocumentReference.Type US CORE TYPE leading to correct hl7 link
DocumentReference.category US CORE CATEGORY leading to correct hl7 link
Encounter extensions leading to correct links
Procedure Proprietary Codes leading to correct links
MedicationRequest ICD codes leading to correct hl7 link
Condition.category US CORE CATEGORY leading to correct hl7 link
=> Fix for Broken Links for various Resources

content/millennium/r4/clinical/diagnostics/questionnaire-response.md, content/millennium/r4/foundation/conformance/structure-definition.md
Description
----
QuestionnaireResponse remove beta tag
PR Checklist
----
=> QuestionnaireResponse remove beta tag

lib/resources/r4/patient.yaml
Description
----
PR Checklist
----
=> Update patient address notes

content/millennium/overview.md
Description
----
PR Checklist
----
- Screenshot(s) of changes attached before changes merged.
-  Screenshot(s) of changes attached after changes merged and published.
=> Update Patient Access Support

content/millennium/r4/base/entities/device.md, lib/resources/example_json/r4_examples_device.rb, lib/resources/r4/device.yaml
Description
----
PR Checklist
----
=> Removes identifier from R4 Device

content/millennium/r4/clinical/medications/immunization.md, content/millennium/r4/proprietary-codes-and-systems.md, lib/resources/example_json/r4_examples_immunization.rb, lib/resources/r4/immunization.yaml
Description
----
Added support for Immunization search by target-disease.
Exposing Immunization.protocolApplied field
PR Checklist
----
=> Immunization target-disease support

content/millennium/r4/foundation/other/health-cards.md
Description
----
Added support for provider access for Health Cards
PR Checklist
----
=> Added support for provider access for Health Cards

content/millennium/r4/clinical/diagnostics/questionnaire-response.md, content/millennium/r4/clinical/summary/family-member-history.md, content/millennium/r4/foundation/conformance/structure-definition.md, lib/resources/example_json/r4_examples_family_member_history.rb, lib/resources/example_json/r4_examples_questionnaire_response.rb, lib/resources/r4/family_member_history.yaml
Description
----
FamilyMemberHistory Updates
PR Checklist
----
=> FamilyMemberHistory Updates

lib/resources/example_json/r4_examples_charge_item.rb, lib/resources/r4/charge_item.yaml
Description
----
PR Checklist
----
Search: 
Read:
=> Support standard codes on R4 Charge Item read/search

lib/resources/example_json/r4_examples_nutrition_order.rb
Description
----
R4 Nutrition Order Incorrect oralDiet.type
PR Checklist
----
----
=> R4 Nutrition Order Incorrect oralDiet.type

content/millennium/r4/clinical.md, content/millennium/r4/clinical/diagnostics/questionnaire-response.md, content/millennium/r4/clinical/summary.md, content/millennium/r4/clinical/summary/family-member-history.md, lib/resources/example_json/r4_examples_family_member_history.rb, lib/resources/r4/family_member_history.yaml
Description
----
Updates to FamilyMemberHistory
PR Checklist
----
=> Updates to FamilyMemberHistory

content/millennium/dstu2/conformance/structure-definition.md, content/millennium/dstu2/medications/medication-administration.md, lib/resources/example_json/dstu2_examples_medication_administration.rb
Description
----
Added infuse-over-time Structure Definition
PR Checklist
----
=> infuse-over-time Structure Definition

content/millennium/r4/foundation/conformance/structure-definition.md
Description
----
PR Checklist
----
=> OPENSVC-20942: Structure Definition[R4] Add infuse-over-time structure definition

content/millennium/r4/clinical.md, content/millennium/r4/clinical/medications.md, content/millennium/r4/clinical/medications/medication-administration.md, layouts/millennium/r4/sidebar.html, lib/resources/example_json/r4_examples_medication_administration.rb, lib/resources/r4/medication_administration.yaml, lib/resources/r4/medication_administration_contained_medication.yaml, nanoc.yaml
Description
----
R4 MedicationAdministration fhir doc
PR Checklist
----
=> R4 MedicationAdministration fhir doc

layouts/api.html, layouts/faq.html, layouts/millennium/overview.html, lib/resources/example_json/r4_examples_capabilitystatement.rb
Description
----
PR Checklist
----
=> R4 Capability Statement update the returned fhir version

content/millennium/r4/base/entities/device.md, lib/resources/example_json/r4_examples_device.rb
Description
----
PR Checklist
----
Before:
After:
=> Device r4 provenance search

content/millennium/r4/clinical/summary/condition.md, lib/resources/example_json/r4_examples_condition.rb
Description
----
Adding revinclude for Condition resource
PR Checklist
----
=> Adding revinclude for Condition resource

content/millennium/r4/base/individuals/patient.md
Description
----
PR Checklist
----
=> Add identifier without system option

content/millennium/r4/base/entities/location.md, lib/resources/example_json/r4_examples_location.rb
Description
----
updated R4-Location with new search parameters
PR Checklist
----
=> Updated R4-Location with new search parameters

content/millennium/r4/clinical/summary/condition.md
Description
----
Added an extra point in implementation note for condition create
Jira Link
----
https://jira2.cerner.com/browse/OPENSVC-21598
PR Checklist
----
=> R4 Condition Updated implementation notes for Create

content/millennium/r4/foundation/documents/document-reference.md, lib/resources/example_json/r4_examples_document_reference.rb
Description
----
changes made for DocumentReference revinclude provenance
Jira link
----
https://jira2.cerner.com/browse/OPENSVC-22402
PR Checklist
----
=> Document reference revinclude

lib/resources/r4/patient_patch.yaml
Description
----
Update patient patch documentation to reflect support for communication preference patch operations.
PR Checklist
----
=> R4 Patient: Update patient patch documentation to reflect support for communication preference patch operations.

content/millennium/r4/base/individuals/patient.md, content/millennium/r4/foundation/conformance/structure-definition.md, lib/resources/example_json/r4_examples_patient.rb, lib/resources/r4/patient.yaml
Description
----
This is a copy of this PR: https://github.com/cerner/fhir.cerner.com/pull/722
PR Checklist
----
Screenshots can be found in this PR: https://github.com/cerner/fhir.cerner.com/pull/722
=> Patient r4 communication preference

content/millennium/r4/clinical/care-provision/goal.md, lib/resources/example_json/r4_examples_goal.rb
Description
----
PR Checklist
----
=> R4 Goal: support _revinclude provenance for goal

content/millennium/r4/clinical/care-provision/care-plan.md, lib/resources/example_json/r4_examples_care_plan.rb
Description
----
updating fhir for careplan revinclude
PR Checklist
----
=> R4 CarePlan: support _revinclude provenance for CarePlan

content/millennium/r4/base/individuals/patient.md, lib/resources/example_json/r4_examples_patient.rb
Description
----
updating fhir doc for patient _revinclude provenance
PR Checklist
----
=> Patient R4 : adding _revinclude for patient provenance

layouts/api.html, layouts/faq.html, layouts/millennium/overview.html, lib/resources/example_json/r4_examples_capabilitystatement.rb
Description
----
PR Checklist
----
=>  revert fhir-version to 4.0.0

content/millennium/r4/foundation/conformance/operation-definition.md
Description
----
Add group-export OperationDefinition
PR Checklist
----
=> Group-export OperationDefinition

content/millennium/r4/clinical/summary/condition.md
Description
----
Update R4 Condition with Encounter based search. Encounter search only returns diagnosis records
PR Checklist
----
=> R4 Condition Provide Encounter search for Diagnosis

content/millennium/r4/financial/general/charge-item.md, lib/resources/example_json/r4_examples_charge_item.rb, lib/resources/r4/charge_item_modify.yaml
Description
----
Adding documentation for chargeitem modify request
PR Checklist
----
=> Chargeitem modify R4 updates

content/millennium/r4/financial/general/charge-item.md, lib/resources/example_json/r4_examples_charge_item.rb, lib/resources/r4/charge_item_create.yaml
Description
----
PR Checklist
----
=> update chargeitem create

lib/resources/example_json/r4_examples_financial_transaction.rb, lib/resources/r4/financial_transaction.yaml
Description
----
Financial transaction guarantor balance account changes
PR Checklist
----
=> R4 Financial transaction guarantor balance account changes

content/millennium/r4/clinical/care-provision/care-team.md, lib/resources/example_json/r4_examples_care_team.rb
Description
----
Added revinclude for CareTeam resource and Updated ID format
PR Checklist
----
=> R4 CareTeam: Added revinclude for CareTeam resource and Updated ID format

content/millennium/r4/clinical/care-provision/care-team.md
Description
----
Added Implementation Notes
PR Checklist
----
=> R4 CareTeam: Added implementation notes

content/millennium/r4.md, layouts/api.html, layouts/faq.html, layouts/millennium/overview.html, lib/resources/example_json/r4_examples_capabilitystatement.rb
Description
----
PR Checklist
----
=> Update fhir version to 4.0.1

lib/resources/example_json/r4_examples_condition.rb, lib/resources/r4/condition.yaml
Description
----
Condition.category incorrect health-concern code system
PR Checklist
----
=> R4 Condition: Condition.category incorrect health-concern code system

content/authorization.md
Description
----
Remove references to limitations of Cerner's platform that are expected to be lifted in a future release.
Screenshot:
PR Checklist
----
=> Remove soon-to-be-stale offline_access guidance

lib/resources/example_json/r4_examples_capabilitystatement.rb
Description
----
Update well-known example
PR Checklist
----
=> Update well-known example

content/millennium/r4/financial/general/insurance-plan.md, lib/resources/example_json/r4_examples_insurance_plan.rb
=> Create fhir.cerner.com documentation for InsurancePlan Read

content/millennium/r4/financial/support/coverage.md
Description
----
Need to update the Coverage Patch Implementation Note.
PR Checklist
----
=> Update fhir.cerner.com for patient level private coverage

content/millennium/r4/financial/general/charge-item.md
Description
----
Remove beta tag from ChargeItem on fhir.cerner.com
PR Checklist
----
=> Remove beta tag from ChargeItem on fhir.cerner.com

lib/resources/example_json/r4_examples_encounter.rb, lib/resources/r4/encounter.yaml
Description
----
Screenshots before the merge: 
PR Checklist
----
=> Update R4 Encounter create to include custom-attribute examples for integer and date_time value types.

content/millennium/r4/clinical/diagnostics/observation.md
Description
----
PR Checklist
----
Screenshots: 
---
=> Social History: Update fhir.cerner.com

content/millennium/r4/base/entities/location.md, content/millennium/r4/proprietary-codes-and-systems.md, lib/resources/example_json/r4_examples_location.rb, lib/resources/r4/location.yaml
Description
----
PR Checklist
----
=> R4 Location Read Sweden Alias - new

content/millennium/r4/base/entities/location.md
Description
----
PR Checklist
----
=> R4 Location Search Sweden Alias Support fixed

content/authorization/authorization-specification.md
Description
----
This document currently contains guidance that has not (yet) been actually implemented by Cerner's FHIR resources; to minimize confusion, replace it with some guidance that _does_ work currently.
PR Checklist
----
Before:
=> Clarify access to fhirUser resources

content/authorization/application-registration-prerequisites.md
Description
----
Update the eTLD+1 documentation in application registration prerequisites.
PR Checklist
----
=> Update eTLD+1 documentation in application registration prerequisites

content/authorization/application-registration-prerequisites.md
Description
----
PR Checklist
----
=> Updating a few references to which domain should have the TXT records

content/soarian/r4/clinical.md, content/soarian/r4/clinical/care-provision.md, content/soarian/r4/clinical/care-provision/care-plan.md, layouts/soarian/r4/clinical.html, layouts/soarian/r4/clinical/care-provision.html, layouts/soarian/r4/sidebar.html, lib/resources/example_json/soarian_r4_examples_care_plan.rb, lib/resources/r4/soarian_care_plan.yaml
Description
----
Request to review R4 Care Plan Documentation. 
PR Checklist
----
=> Soarian R4 CarePlan Documentation

lib/resources/example_json/r4_examples_encounter.rb, lib/resources/r4/encounter_patch.yaml
Description
----
Adding replace capabilities for custom-attribute extensions on Encounter R4. This also adds the ability to add via replace if the id is not present.
Screenshots
----
PR Checklist
----
=> Encounter R4 replace custom-attribute extension

content/authorization.md
Description
----
Remove the section about provider offline access from the Authorization FAQ.
Screenshots
----
Before:
After:
PR Checklist
----
=> Remove provider offline access guidance

lib/resources/example_json/r4_examples_capabilitystatement.rb
Description
----
Update Revocation Endpoint and Supported profiles
PR Checklist
----
Screenshots
----
=> Update Revocation Endpoint and Supported profiles

content/authorization.md
Added additional doc for automatic revocation of offline_access tokens by the authorization server.
Description
----
PR Checklist
----
=> Added additional doc for automatic revocation

content/millennium/dstu2.md, content/millennium/r4.md
Description
----
PR Checklist
----
**BEFORE: DSTU2 example**
**BEFORE: R4 example**
=> Updating CORS requests and response examples.

content/millennium/r4/foundation/security/provenance.md
Description
----
Updating R4 provenance documentation 
SCREENSHOT
----
PR Checklist
----
=> OPENSVC-24021: R4_Provenance_Documentation

content/millennium/r4/foundation/documents/document-reference.md
Description
----
Document reference changes for format and related 
PR Checklist
----
=> Doc-ref changes for format and related

content/soarian/r4/clinical/diagnostics/observation.md
Description
----
PR Checklist
----
=> Soarian Drummond Update

content/millennium/r4/base/workflow/appointment.md, content/millennium/r4/base/workflow/slot.md
Description
Update R4 Slot/Appointment fhir.cerner.com
PR Checklist
----
=> Updated R4 Slot and Appointment With Limitation Note

content/authorization.md
Description
----
Microsoft Edge added new security measures in March 2022 that can be problematic for developers of native SMART applications; document what we know about the causes and resolutions.
PR Checklist
----
=> Add information about scheme flooding

content/millennium/faq/common-issues.md, lib/resources/dstu2/document_reference.yaml, lib/resources/r4/document_reference.yaml
Description
----
PR Checklist
----
=> R4 DocumentReference [fhir.cerner.com] Update the Common Issues section with additional issues

content/millennium/r4/clinical/care-provision/care-plan.md, lib/resources/r4/care_plan.yaml
Description
CarePlan resource needed an update so Author will contain a reference to practitioner
PR Checklist
----
=> R4 -  CarePlan Resource Updates

content/millennium/r4/clinical/summary/procedure.md
Description
----
Add supported references to procedure
PR Checklist
----
=> R4 - Update procedure resources

content/millennium/r4/base/entities/location.md, lib/resources/r4/location.yaml
Description
----
Add location resource updates
PR Checklist
----
=> Add location resource updates

content/millennium/r4/clinical/summary/condition.md
Description
----
Condition resource updates
PR Checklist
----
=> R4 - Update Condition Overview

content/millennium/r4/clinical/summary/allergy-intolerance.md
Description
----
Add supported references to AllergyIntolerance recorder, asserter and note.
PR Checklist
----
=> R4 - Update AllergyIntolerance Overview

content/millennium/r4/clinical/care-provision/goal.md
Description
----
Added multiple goal resource updates
PR Checklist
----
=> R4 - Add goal resource updates

content/millennium/r4/base/individuals/patient.md
Description
----
Add patient resource updates
PR Checklist
----
=> R4 - Add patient resource updates

content/millennium/r4/clinical/medications/immunization.md
Description
----
Add immunization resource updates
PR Checklist
----
=> R4 - Add immunization resource updates

content/millennium/r4/base/entities/device.md, lib/resources/r4/device.yaml
Description
----
Added device resource updates
PR Checklist
----
=> R4 -  Add device resource updates

content/millennium/r4/foundation/security/provenance.md
Description
----
Remove Agent.onBehalfOf from returned fields list and add supported profiles
PR Checklist
----
=> R4 - Update Provenance Overview

content/millennium/r4/clinical/medications/medication-request.md
Description
----
Updates for the FHIR resource: MedicationRequest.
PR Checklist
----
**Screenshot(s) before the changes:**
----
**Screenshot(s) after the changes:**
----
=> R4 - Update MedicationRequest Overview

content/millennium/bulk-data.md, content/millennium/bulk-data/group-export.md, layouts/api.html, layouts/faq.html, layouts/millennium/bulk-data/sidebar.html, layouts/millennium/overview.html, layouts/millennium/r4/sidebar.html, lib/helpers/attributes_helper.rb, lib/resources.rb, lib/resources/example_json/r4_examples_group_export.rb
Description
----
Documentation for FHIR Bulk Data Export
Local Validation
----
PR Checklist
----
=> FHIR Bulk Data Export Documentation

content/millennium/r4/clinical/medications/medication-request.md
Description
----
Fix the TOC and one of the Example URLs for R4 MedicationRequest
Local Validation
----
PR Checklist
----
=> Fix R4 MedicationRequest TOC and Formatting of Example URL

content/millennium/bulk-data.md, content/millennium/bulk-data/group-export.md
Description
----
FHIR Bulk Data Documentat Updates: add "Media Types" and "Authorization" section in the overview. Use full-url for OperationOutcome URL.
Local Validation
----
PR Checklist
----
=> Bulk Data Documentation Updates

content/authorization.md
Description
----
In preparation for the rollout of Bulk Data, add notes on JWT authentication.
PR Checklist
----
=> Add notes on JWT authentication

content/millennium/r4/clinical/diagnostics/observation.md, lib/resources/example_json/r4_examples_observation.rb, lib/resources/r4/observation.yaml
The only change with the PR https://github.com/cerner/fhir.cerner.com/pull/893
is that now we have the profiles in alphabetical order. ([commit](https://github.com/cerner/fhir.cerner.com/pull/911/commits/4eba3a90a5b76960d608256e818c7a482baf6aac))
=> R4 observation updates

content/millennium/r4/clinical/summary/condition.md
Description
----
Encounter parameter description and notes now specifies that all problem-list-item conditions of a patient are returned when encounter is provided
PR Checklist
----
=> R4 - Update Condition encounter description and notes

content/millennium/r4/foundation/documents/document-reference.md, lib/resources/example_json/r4_examples_document_reference.rb
Description
----
PR Checklist
----
=> R4 DocumentsReference Read and Search examples are updated

content/millennium/r4/foundation/documents/document-reference.md, lib/resources/example_json/r4_examples_document_reference.rb, lib/resources/r4/document_reference.yaml
Description
----
R4 Document Reference  create and update workflow updation
PR Checklist
----
=> R4 Document Reference  create and update workflow updation

content/authorization/application-registration-prerequisites.md
Description
----
Add a FAQ to address a topic that we've been asked about.
PR Checklist
----
=> Add FAQ to Application Registration Prerequisites

content/millennium/r4/base/workflow/appointment.md, lib/resources/example_json/r4_examples_appointment.rb
Description
----
PR Checklist
----
=> Appointment Read/Search returns isReschedulable and isCancelable extension

content/millennium/r4/base/entities/organization.md
added a new note to the organization search feature, under the section 'Search all Organizations' :
- 'This is not recommended for sites that have a large number of organizations and will not be performant.'
Description
----
PR Checklist
----
=> organization-r4-search-notes-update

content/millennium/r4/base/individuals/patient.md
under r4 -> base -> individuals -> patinet -> extensions the hyperlink for 'Patient Prefered Contact' was updated with:
- https://www.hl7.org/fhir/defining-extensions.html
Description
----
PR Checklist
----
=> patient-r4-extentions-hyperlink-updated

content/millennium/r4/base/entities/organization.md, content/millennium/r4/base/individuals/practitioner.md
Description
----
PR Checklist
----
Screenshot Before Merging & Before code changes
Screenshot Before Merging & After code changes
=> Update US_Core reference link in Practitioner and Organization

content/millennium/r4/clinical/diagnostics/diagnostic-report.md, content/millennium/r4/foundation/documents/document-reference.md
Description
----
Updated _count description
PR Checklist
----
Before merge
----
=>  R4 DocumentReference resource updates

content/millennium/r4/clinical/diagnostics/diagnostic-report.md
Description
----
PR Checklist
----
=> R4_Diagnostic_Report_Functional_Overview_updated

content/millennium/bulk-data.md, content/millennium/bulk-data/group-export.md, lib/resources/example_json/r4_examples_group_export.rb
Description
----
- Remove Beta tag from Group Export operation
- Other nit changes for GA
Local Validation
----
PR Checklist
----
=> Update bulk-data documentation for GA

content/authorization.md
Description
----
This document has several mentions of outdated draft specifications; clean them up.
PR Checklist
----
=> Update discussion of drafts

content/millennium/r4/clinical/care-provision/care-team.md, lib/resources/example_json/r4_examples_care_team.rb
Description
----
In [http://fhir.cerner.com/millennium/r4/clinical/care-provision/care-team/](url) we have added details for CareTeam.participant.period field.
PR Checklist
----
=> Add_Details_For_CareTeam_participant_period

content/millennium/bulk-data/group-export.md
FLATFHIR-1199 Added group size recommendation
----
PR Checklist
----
=> FLATFHIR-1199 Update group-export.md

content/millennium/r4/base/workflow/appointment.md, lib/resources/example_json/r4_examples_appointment.rb
=> Appointment Read/Search returns Group Appointment Id extension

lib/resources/r4/financial_transaction.yaml
Description
----
PR Checklist
----
=> Update to Financial Transaction FHIR API documentation

lib/resources/r4/patient_patch.yaml
Description
----
Patient patch replace Communication Preference
PR Checklist
----
=> Patient patch replace Communication Preference

content/millennium/r4/base/individuals/patient.md, content/millennium/r4/clinical/diagnostics/observation.md
Description
----
updated notes for Observation create and patient search
PR Checklist
----
=> updated notes for Observation create and patient search

content/millennium/r4/clinical/diagnostics/observation.md
Description
----
added new search by id parameter for observation
PR Checklist
----
=> added new search parameter for R4 observation

content/millennium/r4/clinical/diagnostics/observation.md
Description
----
updated notes for Observation search
PR Checklist
----
=> updated notes for Observation search

content/millennium/r4/base/workflow/appointment.md, lib/resources/example_json/r4_examples_appointment.rb, lib/resources/r4/appointment_patch.yaml
Description
----
Reschedule appointment slot patch
PR Checklist
----
=> Reschedule appointment slot patch

content/authorization.md
Description
----
Our terminology was a bit sloppy here and there are better citations; clean this section up.
PR Checklist
----
=> Clarify JWT Authentication

content/authorization.md
Description
----
We have gotten some questions from third-party vendors about how (and why) this functionality is currently implemented; capture their answers.
PR Checklist
----
=> Add documentation about access token size limitations

lib/resources/example_json/r4_examples_observation.rb
Description
----
Observation r4 Expose standard code display
PR Checklist
----
=> Observation r4 Expose standard code display

content/millennium/r4/clinical/diagnostics/observation.md
Description
----
updated notes for R4 Observation search by _id
PR Checklist
----
=> updated notes for R4 Observation search by _id

content/millennium/r4/foundation/other/binary.md
Description
----
Update -ccd-if Parameters R4
PR Checklist
----
=> Update -ccd-if Parameters R4

content/millennium/dstu2/encounters/encounter.md, lib/resources/example_json/dstu2_examples_encounter.rb
Description
----
added new example for DSTU2 Encounter Retrieve by id
PR Checklist
----
=> added new example for DSTU2 Encounter Retrieve by id

content/millennium/r4/financial/general/financial-transaction.md, lib/resources/r4/financial_transaction.yaml
Description
----
Adding Apply First in First Out extension to 'Basic' resource.
PR Checklist
----
=> Financial Transaction Apply First In First out extension

content/millennium/r4/base/workflow/appointment.md, lib/resources/example_json/r4_examples_appointment.rb, lib/resources/r4/appointment_patch.yaml
Description
----
Appointment Resource action-comment extension and Appoint.comment patch operation.
PR Checklist
----
=> Appointment Resource action-comment extension and Appoint.comment patch operation

lib/resources/r4/consent.yaml
Description
----
In preparation for migrating to Oracle docs, we are reviewing and correcting any inconsistencies, typos, broken links, etc. This PR aims to correct any of the above that needs to be addressed within Consent/Contract and any other information directly referenced by it.
* Fixed URL in details for scope
**Before**
**After**
* Fixed URL in details for purpose
**Before** (same 404 as above)
**After**
PR Checklist
----
=> fixing URLs for scope and purpose in consent

content/millennium/r4/foundation/security/consent.md, lib/resources/example_json/r4_examples_consent.rb
Description
----
Updated examples for `Search by Id` and `Search by Actor` with updated data which was previously showing outdated data
**Before**
**After**
---
**Before**
**After**
---
Consistency with formatting in description by adding backticks
**Before**
**After**
PR Checklist
----
=> Consent updated examples

content/millennium/dstu2/general-clinical/allergy-intolerance.md
Several nitpick/formatting updates in this one. Most of it was in good condition.
Validated that API calls behave as expected, in-line with the document's examples.
Description
----
- Grammatical updates, specifically in the Overview.
- Adjusted parameter table to be more condensed, with an explainer following it
- Anonymized X-ref-ID's under the Create/POST and Update/PUT examples
PR Checklist
----
Old Overview:
New Overview:
Old Parameters section:
New Parameters + explainer section:
X-Ref-ID's anonymized - Old values:
X-Ref-ID's anonymized - New values:
=> Updated AllergyIntolerance DSTU2 resource

content/millennium/dstu2/scheduling/appointment.md, content/millennium/r4/base/workflow/appointment.md, lib/resources/dstu2/appointment.yaml
Overview
before:
after:
Search notes
before:
after:
Search params
before:
after:
Update notes
before:
after:
Update errors
before:
after:
Create/Update field definitions
before:
after:
Note that the recent R4 Appointment changes included invalid links, so this also updates them to match these updates.
PR Checklist
----
=> Update DSTU 2 Appointment documentation

content/millennium/dstu2/medications/immunization.md
Just a handful of changes on this one, including some re-wording of Overview and Implementation Notes sections to be more descriptive / in a similar style to other resources that were recently updated.
Description
----
- Expanded the Overview Section, and more closely matches the verbiage used by HL7.org itself now.
- Now includes direct links out to the `AllergyIntolerance` and `MedicationAdministration` resources.
- Consolidated Disclaimer, Error, and Outcome sections towards the top.
- Adjusted parameters table's details.
- Expanded on Implementation Notes to match the performance of the API, and explain requirements and expected behavior of each search …
=> Updated Immunization DSTU2 Resource

content/millennium/r4/base/entities/device.md, content/millennium/r4/base/individuals/patient.md, content/millennium/r4/base/management/encounter.md, content/millennium/r4/clinical/care-provision/care-plan.md, content/millennium/r4/clinical/care-provision/care-team.md, content/millennium/r4/clinical/care-provision/goal.md, content/millennium/r4/clinical/diagnostics/diagnostic-report.md, content/millennium/r4/clinical/medications/immunization.md, content/millennium/r4/clinical/medications/medication-request.md, content/millennium/r4/clinical/summary/allergy-intolerance.md, content/millennium/r4/clinical/summary/condition.md, content/millennium/r4/clinical/summary/procedure.md, content/millennium/r4/foundation/documents/document-reference.md, lib/resources/example_json/r4_examples_nutrition_order.rb
Description
----
Update FHIR documentation for RevInclude supported resources
PR Checklist
----
=> Update FHIR documentation for RevInclude supported resources

content/millennium/r4/clinical/medications/medication-administration.md
Many formatting updates in this one, and substantial re-wording of sections to be more descriptive and in a similar style to other resources that were recently updated.
Description
----
- Rewriting of Overview, including link over to `Immunization` Resource.
- Condensed / removed duplicate "IMPORTANT NOTE" sections throughout document.
- Adjusted non-displayed characters of the Custom Extensions table - don't need that many hyphens.
- Adjustments to Search Parameter Table and Implementation Notes sections.
- Matched currently approved formatting for the table.
- Noted parameters that accept comma-separated lists.
- Rewrite of `effective-date` section to match …
=> Updated MedicationAdminstration R4 Resource

content/millennium/dstu2/individuals/practitioner.md, lib/resources/dstu2/practitioner.yaml, lib/resources/example_json/dstu2_examples_practitioner.rb
Description
----
* Fields
* Updated links to 'https'
* Cleaned up names
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/2cd31791-a498-48f0-afa1-455f7447af72)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/b8ddabf6-a334-4bfe-8a86-73d7e0e35446)
* Moved disclaimer and error message (see above)
* Updated 'id' to 'ID' throughout
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/f531cfbe-bb2b-4b90-92ac-1a1cb29864b8)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/a2c229b6-02e3-49af-8f3b-c7b91d5cfe30)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/bd6f19ec-a61c-47e3-b97c-3124cfcda276)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/c3061cac-46f9-4da0-9206-f9fbdee26427)
PR …
=> dstu2 Practitioner updates

content/millennium/r4/base/individuals/patient.md, lib/resources/r4/patient.yaml, lib/resources/r4/patient_patch.yaml
Description
----
Changes:
* "id" -> "ID" throughout
* moved error and disclaimer
* misc. http -> https
* field list
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/d2c4c5c3-a49b-45b1-a590-acfcc793628f)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/dc405827-6b24-47d4-96b0-f6a87fcedd09)
* search params
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/1f8253dc-75c2-4301-95ae-bc7eb6ec6eae)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/587c4a57-31ab-442f-8d42-e704b53c41d6)
* search notes
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/a9fcda67-b390-4d66-a02f-5929f6442173)
* ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/7b263e03-0a07-406d-89dc-06587f4c6133)
* patient …
=> R4 Patient formatting and standard updates

content/millennium/r4/clinical/medications/immunization.md
Description
----
[R4][Immunization] Support search by _lastUpdated
PR Checklist
----
=> [R4][Immunization] Support search by _lastUpdated

content/millennium/r4/clinical/medications/immunization.md
Description
----
[R4][Immunization] Documentation Update
PR Checklist
----
=> [R4][Immunization] Documentation Update

content/millennium/r4/foundation/documents/document-reference.md, lib/resources/example_json/r4_examples_document_reference.rb
Description
----
Added nil status examples for DocumentReference
PR Checklist
----
=> DocumentReference_Nil_status_examples_added

content/millennium/r4/clinical/medications/immunization.md, content/millennium/r4/clinical/summary/allergy-intolerance.md, content/millennium/r4/clinical/summary/condition.md, content/millennium/r4/clinical/summary/procedure.md, layouts/header.html
Description
----
Added new Last Updated Parameter for R4 Condition and Procedure resources.
Screenshots:
---
PR Checklist
----
=> Added new search parameter for R4 Condition,Procedure and Added a notification in the header.

content/millennium/r4/clinical/summary/condition.md
Description
----
Condition resource Implementation Notes update
PR Checklist
----
=> Condition resource Implementation Notes update

content/millennium/r4/base/individuals/practitioner.md
Description
----
[R4] Practitioner resource update
PR Checklist
----
=> [R4] Practitioner resource update

content/millennium/r4/clinical/care-provision/service-request.md, lib/resources/example_json/r4_examples_service_request.rb
Description
----
[R4] ServiceRequest support _revincludes:Provenance:target
PR Checklist
----
=> [R4] ServiceRequest support _revincludes:Provenance:target

content/millennium/r4/base/workflow/appointment.md
Description
----
Added patient persona for R4 appointment
PR Checklist
----
Before Merge:
[
](url)
=> Added patient persona for R4 appointment

content/millennium/r4/base/management/encounter.md, content/millennium/r4/clinical/care-provision/nutrition-order.md, lib/resources/example_json/r4_examples_nutrition_order.rb
Description
----
Encounter support for _lastupdated and NutritionOrder support for _revinclude
PR Checklist
----
=> Encounter support for _lastupdated and NutritionOrder support for _revinclude

content/millennium/r4/financial/support/coverage.md, lib/resources/example_json/r4_examples_coverage.rb
Description
----
[R4] Coverage Retrieve by id
PR Checklist
----
=> [R4] Coverage Retrieve by id

lib/resources/example_json/r4_examples_condition.rb
Description
----
Condition example update
PR Checklist
----
=> R4 Condition example update

content/millennium/r4/clinical/medications/medication-request.md
Description
----
PR Checklist
----
=> R4 MedicationRequest NLLConditionsPharmaceuticalBenefitsAct extension

lib/resources/r4/provenance.yaml
Description
----
[R4][Provenance] documentation for create
PR Checklist
----
=> [R4][Provenance] documentation for create
